### ISSUE TITLE
Bug - deleted explanation is not being deleted in the iSoQ table

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#102]
Hi Damian,

So now the explanation is deleting in the evidence profile in the worksheet, but it is not deleting in the iSoQ table. 

See:
![image](https://user-images.githubusercontent.com/72507850/117723806-c588dd00-b1da-11eb-8cb2-82705071eb6d.png)
![image](https://user-images.githubusercontent.com/72507850/117724006-0da7ff80-b1db-11eb-9c2e-6397a5860391.png)

**Comment by damian-garrido** [comment]
i made an update on test server, can you check please!

**Comment by damian-garrido** [comment]
published
