### ISSUE TITLE
Explanations not deleting from components after duplication

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#105]
I discovered the following bug:

- I create a project
- I duplicate the completed project
- I delete the assessment for Relevance and Overall Assessment
- I duplicate the new unfinished project
- In the duplicate the selection for relevance is not there, but the explanation still appears in the explanation box
![image](https://user-images.githubusercontent.com/72507850/117886484-3269a900-b2a7-11eb-92c5-e437ca5d9952.png)

**Comment by damian-garrido** [comment]
i could reproduce this
so, what is the best solution?
when i click on "clear my selection" this also need to remove the notes?
or
when i clone a project, no notes should be copied?
saludos

**Comment by MJWainwright** [comment]
Ah I think I got confused between the "Notes" and the "Explanation". It's ok for the Notes to remain. When I click "clear my selection" it should clear the radio buttons and the explanation box, but NOT the notes. So I think it is correct how it is.

**Comment by MJWainwright** [comment]
Will re-open if I find the issue again, but I think it's ok
