### ISSUE TITLE
Missing extracted data on second, third, fouth, etc. duplicate

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#106]
Hiya! I found a bug related to duplicates. I created a template project for iSoQ training. I duplicated the template project 3 times so that each of my three groups had their own copy.

- The first duplicate was perfect.
- However, the second and third duplicates were missing extracted data.

I was able to re-produce this error on the test site. See if you can reproduce it:

- create a project - add some data in all My Data fiels, add one finding to iSoQ, add Extracted Data to the Worksheet.
- duplicate the project - check the duplicate and see all is fine
- duplicate the original project a second time - check and you will see that the Extracted Data table in the worksheet is blank (the data is missing.

**Comment by damian-garrido** [comment]
i can confirm, also confirm that the data is no missing, i think is just only bad related. im going to fix this.

**Comment by damian-garrido** [comment]
could you check if the problems still happening on the test server please.

**Comment by MJWainwright** [comment]
I checked on the test server without clearing my cache and it looks fixed. I was not able to reproduce the error. Let me know when it is published to production server and I will check it again. Thanks!
