### ISSUE TITLE
Users with "view only" rights are not able to see the worksheets

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#107]
I think this error occured when we de-implemented the freezing function. At the workshop I just gave, one person in a group was given edit and view rights, and all others view only (I thought this would reduce risk of them accidentally editing at the same time). However, users with "view only" were supposed to be able to see the worksheet but they could not. it looked like this:
![image](https://user-images.githubusercontent.com/72507850/118298168-06cd0580-b4d7-11eb-99e8-0f19bdb7304d.png)

Are you able to fix this?Users with "view only" rights must be able to see all the pages in iSoQ, including the Worksheets for each finding. 

Let me know if this isn't clear.

**Comment by damian-garrido** [comment]
i could replicate this, so, when i have some time i will tray to smash this.

**Comment by damian-garrido** [comment]
hi,
could check if this issue is fixed or not.
i made a new update for this.
saludos!

**Comment by MJWainwright** [comment]
Checked, all good on both the test server and the production server. Thanks!

**Comment by MJWainwright** [comment]
I'm closing as I see this as fixed on production server already
