### ISSUE TITLE
Option to "change password" is missing

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#108]
Hi Damian,

Simon brought up an interesting point and that is that we have nowhere for users to change their password. They have to guess that they change their password by saying they have forgotten their password. Can we please implement a change password feature? I don't know if this would be done only from within iSoQ (when logged-in), or from the main webpage. Do you know how it is in iSoF and if we can just copy that?

Thanks!

**Comment by MJWainwright** [comment]
@damian-garrido . I think this one is quite important to implement. Is it possible?

**Comment by damian-garrido** [comment]
it's possible!

**Comment by MJWainwright** [comment]
@damian-garrido . How are we doing with this enhancement?

**Comment by ranazahroh** [comment]
Hi Damian, I have tested this and it works perfectly. I think this is ready to be pushed to the production server. Thanks!
