### ISSUE TITLE
check groups and printing on Summary of Qualitative Findings Table

### ISSUE THREAD

**Issue by damian-garrido** [epistemonikos/isoq#109]
check the functionality of this using groups

**Comment by MJWainwright** [comment]
@damian-garrido 
I've checked and it is not working on the test server both when I use groups and when I don't use groups. When I click Print or Export the buttons don't appear, only the preview of the table changes

![image](https://user-images.githubusercontent.com/72507850/129244574-5621cc1f-4135-450d-b757-50bcf4fef95b.png)

**Comment by MJWainwright** [comment]
@damian-garrido . You can close this one, it looks like it has been resolved
