### ISSUE TITLE
revisar que no quede el grupo seleccionado al crear un nuevo finding

### ISSUE THREAD

**Issue by damian-garrido** [epistemonikos/isoq#110]
al crear un finding cuando hay grupos, este permite seleccionar dentro del listado de grupos, pero cuando se crea un nuevo finding, el grupo viene precargado, revisar borrar variable

**Comment by damian-garrido** [comment]
hi @MJWainwright could you also check this!

**Comment by MJWainwright** [comment]
Hi @damian-garrido. Checked on test server without clearing cash and it is fixed. Can you do an update to the production server on Monday or Tuesday next week and then I will test it there?
