### ISSUE TITLE
iSoQ not accepting an .RIS import from reference manager RefWorks

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#112]
Hiya!
I user reached out to say she exported her refs from the software refworks as .RIS but then when she chooses that file in iSoQ nothing happens, the "upload button" is dead. I reproduced this.

When I imported her .RIS exported from refworks in my Endnote software and from there exported to .RIS and uploaded to iSoQ it worked. So it might be something about how iSoQ reads .RIS files exported from refworks. Refworks is a common software, so we do want to be compatible with it.

i will send you to two RIS files in an email

**Comment by ranazahroh** [comment]
Hi @damian-garrido I have tested this with RefWorks RIS file from Simon and it can be imported flawlessly now! I think the changes are ready to be pushed to the server. Thank you!
