### ISSUE TITLE
Print/Export button not displaying properly and groups buttons not disappearing in export mode

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#113]
When I click "Print or Export" the button does not change back to "edit" as it should. 

In this image I have already clicked "print or export" - It has removed all of the buttons except for the "groups" buttons which should also not appear in print/export mode. AND the button should now say Edit but it continues to say "print or export"

![image](https://user-images.githubusercontent.com/72507850/139082031-7d523c62-05e1-4f5d-b43e-7a430d88c0ae.png)

**Comment by damian-garrido** [comment]
fixed!

**Comment by MJWainwright** [comment]
This appears to be resolved so I am closing
