### ISSUE TITLE
v2 enhancement - leaving a project or removing it from workspace

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#115]
Not urgent but realised that once a project has been shared with a user there is no way for a user to "leave it" or "remove it" from the workspace. Their only option is to contact the creator of the project and ask them to "unshare". Adding the ability to "leave" or "remove" a project is something we could consider for v.2

**Comment by damian-garrido** [comment]
@ranazahroh i made an update on the test server, could you see if this fit to the requierements, thanks

**Comment by ranazahroh** [comment]
Hi Damian, I have tested this and it works like wonder! I think it is ready for public server. We can perhaps close this ticket? @damian-garrido

**Comment by ranazahroh** [comment]
Hi Damian, I have tested this again, and it works perfectly. I think this is ready to be pushed to the production server. Thanks!
