### ISSUE TITLE
Import from mendeley failure

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#116]
A user exported her reference list from the reference software mendeley as an .ris file but the references were then not displayed correctly. In many cases the "year" appeared as "undefined".  I will send .ris file separately for you to test.

**Comment by damian-garrido** [comment]
i was looking more in detail about this.
the Publication Year should be using the tag
PY  - SomeYear
but, in the ris that you send me, only made reference to 
Y1  - SomeData
according to wikipedia
Y1 means Primary Date
and
Y2 means Access Date

i need to investigate if most of the software use PY over Y1 or are equal, also, i was search that this kind of date format is valid (2020///) and at the end of the line you could use something like 2020/12/25/Mid of Summer as a valid date!
so, i need to think on how could the platform store and format this kind of dates

**Comment by MJWainwright** [comment]
Ok, sounds complicated! In the meantime I will try to collect more examples of Mendeley exports for you.

**Comment by damian-garrido** [comment]
i made some updates with this.
now, the platform support both (PY and Y1)
i'm not sure if a reference could have both at the same time, but for the moment, with the examples that you send me, always have one of them.
the update is published on the test server.
please, check and tell me if work to you.

**Comment by MJWainwright** [comment]
@damian-garrido . Sorry Damian, I am having difficulty checking this because I don't have the Mendeley program. What do you think we should do? keep the ticket open or go ahead and publish the fix you've done to the production server without me checking it?

**Comment by ranazahroh** [comment]
@MJWainwright @damian-garrido is this issue solved? Do you want me to test it? I see Mendeley is free, so I can test it if this has been solved yet not tested.

**Comment by damian-garrido** [comment]
@ranazahroh please! could you do this!
also, could you share with me some RIS files generated with this app.
its possible you could use a file with a lot of information, because, sometimes, some apps use different formats for threat the information of authors or publication year for example.
thanks!

**Comment by damian-garrido** [comment]
Hi @ranazahroh i fix this issue, at least the related with date formating
so, for example, if a date is formated like 2022///, the app could understand this and show the correct information.
can you check if you have this problem.? i could send you the original RIS that have this issue.

**Comment by ranazahroh** [comment]
Hi Damian, sorry I did not realised you mentioned me on Aug 12!
I can definitely check this, I am installing Mendeley on my computer now. Can you send me the original RIS that have this issue through emai? Thanks @damian-garrido

**Comment by ranazahroh** [comment]
Hi Damian, I have tested this with new generated RIS files from Zotero and Mendeley. The year appeared correctly, yet unfortunately the title did not. What appeared on the title is the journal name instead. I have sent details on email including new RIS files and screenshots. Let me know if you need me to test more, I will be able to do it more promptly now as I have returned back to Melbourne :) have a lovely day @damian-garrido !

**Comment by ranazahroh** [comment]
Hi @damian-garrido, I tested this already using 8 RIS files generated from Mendeley and Zotero, and all successfully imported correctly. I think this can be pushed to the production server. Thanks!
