### ISSUE TITLE
User feedback for enhancement to display of studies with same author/year in tables

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#129]
A user had a number of references that had the same first author and the same year. When she was inputting data into tables for these studies it was very hard for her to know which study was which (since the tables only display the first author last name and year). She reached out and I told her she would have to see the order they were listed on by clicking View/edit references in My Data or the Worksheets as in this view she could see the titles of the article. This obviously wasn't very user friendly. I wonder if we could display the title of the article as a tooltip when the user hovers over each author(s)/year in the first column of the tables? 

What do you think?

**Comment by damian-garrido** [comment]
yes! i was thinking the same thing. i think this is a good option.

**Comment by MJWainwright** [comment]
Great!

**Comment by damian-garrido** [comment]
i added this to the test server

**Comment by MJWainwright** [comment]
@damian-garrido 

Sorry I lost track of this! I just checked on test server. The title tooltips are displaying in the My Data section, but they are entirely missing from the modals that pop-up from the Evidence Profile in the Assessment Worksheets (all three tables), and two of the tables are missing them on the mainWorksheet page (not displaying in characteristics of studies or methodological limitations) . See below

![image](https://user-images.githubusercontent.com/72507850/174274720-f2ef3692-426c-439d-8c21-bd458a50d32d.png)

![image](https://user-images.githubusercontent.com/72507850/174274776-411801de-8923-4bb2-a2dc-4bf7856008a9.png)

**Comment by MJWainwright** [comment]
@damian-garrido . How are we doing on fixing the display of the tooltips (above)?

**Comment by damian-garrido** [comment]
exactly, this was only applied on the My Data table, im going to replicate to the other views. i will let you know when this is published on the test server. thanks!

**Comment by damian-garrido** [comment]
this improve is available on the test server

**Comment by MJWainwright** [comment]
@damian-garrido . I've checked this on the test server. Looks good! Please publish it to the production server
