### ISSUE TITLE
Import of RIS from Distiller software - some authors missing

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#133]
A user sent me an RIS file exported from Distiller SR - https://www.evidencepartners.com/products/distillersr-systematic-review-software. It did import to iSoQ, but a number of the studies say "no authors" rather than author/date. Will send you the RIS file separate to have a look at.

**Comment by damian-garrido** [comment]
some references dont have authors, this is why some of them are missing

**Comment by ranazahroh** [comment]
Hi @damian-garrido, I do not have RIS file from Distiller software, it is paid software, so I cannot generate the file by myself. Can you share the file you have with me Damian? So I can test the improvement you made on the test server

**Comment by ranazahroh** [comment]
Damian, I have received a RIS file from a friend of mine who used Distiller. I think all details are uploaded correctly. Only the name shows the first letter of the first name like below **"A Aggarwal et al."**, is it possible to make it to only **"Aggarwal et al."** without the **"A"**? Looking forward to hearing from you. I have sent the RIS file through email for your reference.

**Comment by ranazahroh** [comment]
Hi Damian, I asked Simon and he said that the one with initial is fine, as it is how the user save it on their reference manager. So no need to delete the initial ("A") when importing.

I have tested with another RIS file Simon sent and it is uploaded successfully. We are waiting for another RIS file from Distiller for testing and if that one works fine, I think this issue will be able to be closed. I will keep you posted.
