### ISSUE TITLE
Import of RIS from Eppi Reviewer software - some authors missing

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#134]
A colleague sent me an RIS file exported from EPPI Reviewer software (https://eppi.ioe.ac.uk/CMS/Default.aspx?alias=eppi.ioe.ac.uk/cms/er4&). Again, it imported fine but some authors are missing when you click "view references". Not sure why that is. Will send ris file by email

**Comment by damian-garrido** [comment]
same as #133

**Comment by ranazahroh** [comment]
Hi @damian-garrido - thank you for implementing the changes! We are able to import .txt RIS now and all refs from EPPI Reviewer are all able to be uploaded successfully. We can push this to the production server Damian.
