### ISSUE TITLE
Feedback from user for enhancement - moving between worksheet and iSoQ page

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#142]
A user has said that her team overall found iSoQ helpful but one thing that bothered them was that when you work on assessing a finding (i.e. on the GRADE-CERQual Assessment Worksheet page) and then click "return to iSoQ table", the display is bumbed back to showing the first finding in the iSoQ table, rather than the finding that had just been worked on. The users would like to see iSoQ be able to hold the position on the page. For example, if you clicked "Complete GRADE-CERQual Assessment" for finding #16, then completed the assessment in the Worksheet and clicked "return to iSoQ table", you would see finding #16 (whereas at the moment, you won't, you will see the top of the iSoQ table and will have to scroll down to finding #16 to then move on to finding #17).

**Comment by MJWainwright** [comment]
related to #51

**Comment by damian-garrido** [comment]
hi @MJWainwright 
there is a new version that resolve this issue, can you check this please.
saludos
