### ISSUE TITLE
Updates to length of videos displayed on Help page

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#144]
I have updated 3 help videos which has made them longer and so the time in square brackets on the Help page needs updating as follows:

4. Importing references for included studies [3:00 min]
7. Importing a characteristics of studies table [8:54 min]
9. Importing a methodological assessments table [9:52]

Thanks!

**Comment by damian-garrido** [comment]
was fixed on the test server!

**Comment by MJWainwright** [comment]
Checked! Looks good, thanks. Can be published to production server:)

**Comment by ranazahroh** [comment]
@damian-garrido @MJWainwright I see that these changes have been reflected on production server, can we now close this ticket? Thank you!
