### ISSUE TITLE
Unable to add extracted data for one study

### ISSUE THREAD

**Issue by ranazahroh** [epistemonikos/isoq#146]
Hi @damian-garrido, one user contacted me and she found a glitch where she was unable to add extracted data of one study (the study does not appear under the theme/finding).

She has uploaded all of the references, study characteristics and methodological assessment tables have all been uploaded. 

When entering extracted data for one of our themes, one study is not displayed in that section to enter the extracted data - even though it is there in the list of studies for that theme, in the study characteristics table for that theme and also for the quality assessment table for that theme.

The same study provides evidence for other themes and the problem is not replicated there. It is displayed in the list for extracted data to be added and this was done successfully.

User thinks the glitch may have happened because, before the CERQual assessments were started, this reference was deleted in error and a new table of characteristics and quality assessment uploaded. 

At this point, there has been a lot of work done in uploading extracted data and doing the assessments for the themes within the study. So user has couple of questions:

- User was wondering if the new study characteristics table is uploaded, will all of the work they have done deleted? 
- User said that the tables uploaded has data missing from this table - empty cells where the study did not provide the information - which user presumed is the cause of the missing data alert. She asked if she can edit the table in the platform or do we have to edit it externally and upload a new version?

I just tested uploading new characteristics of table with content edited to my iSoQ project and editing it on the portal, and seems there is no change on the assessments made to iSoQ table. Is this correct?

I have suggested user to add a new theme with that reference supporting it and see if she can add the extracted data. If this does not work I suggest her to invite me to the project so I can see the error, and also asked her to send the files that she uploaded and the new one that she would like to upload - so we can see how different the content will be. I am wondering if you have any suggestions on what the user should do for this issue? And if there is any information needed?

**Comment by damian-garrido** [comment]
let me check this, and i will have a more accurated response. 
i'll be back soon with this. 
thanks

can you request for the files that she use, or maybe share the project with me, doing this is more easy to me to check whats happening with the data.

thanks!

**Comment by ranazahroh** [comment]
Hi Damian, this issue has been solved! We found out the issue was because user created the theme, yet deleted the study afterwards, and adding it again without updating the study on the theme. This has been resolved by creating a new theme. I think  we can close this issue now. Thank you!
