### ISSUE TITLE
Cannot import RIS file with .txt file format

### ISSUE THREAD

**Issue by ranazahroh** [epistemonikos/isoq#149]
Dear @damian-garrido, some software like EPPI Reviewer exported the references to RIS but with .txt instead of .ris format. I wanted to test your debugging with references generated by EPPI Reviewer but I cannot upload the references with .txt format, despite the "my data" page said the following: **STEP 2: Import the .ris/.txt file into iSoQ.** - can you please check on this matter and if we can enable the .txt format upload? I will upload the file to the email that I will send shortly. Thank you!

**Comment by damian-garrido** [comment]
an update was published on test server :)

**Comment by ranazahroh** [comment]
I have tested this and it successfully and correctly uploaded refs from EPPI Reviewer. This is ready to be pushed on production server. Thanks @damian-garrido
