### ISSUE TITLE
consistent on exportable doc in Browser section view

### ISSUE THREAD

**Issue by damian-garrido** [epistemonikos/isoq#150]
It works but what appears is not consistent, for example on "National implementation of the World Health Organization Model List(s) of Essential Medicines- a qualitative evidence synthesis" headings of evidence profile and summary of findings appears, despite it does not appear when not exporting. On "Test of publish function" project, evidence profile appears despite no data on the dashboard. 
Can you make the exported data/printed data be consistent with what appears on the isoq dashboard?

**Comment by ranazahroh** [comment]
Works well Damian! Thank you! Couple of feedback from me:

- I think we talked about what we have in terms of content on word and pdf should be the same, but I see it is different, whereas, on pdf generated, hyperlinks still exist to see evidence profile. Is it possible to make the content generated on word and pdf the same?

- I also realized that the table formatting for the evidence profile is a bit off, I attached the screenshot on the email I sent. Please see a circle in blue. Is it possible to make the line on the table the same line as on SoQF table?

Please let me know if you need further clarification.
