### ISSUE TITLE
Unusual display of published iSoQs in Browse

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#160]
There are a number of odd things on the published iSoQ projects on the Browse page. Can you please investigate this from your side before I contact the users directly? Also makes me think we need to have some sort of disclaimer saying that iSoQ doesn't review published iSoQs for quality or fidelity to the GRADE-CERQual approach. To discuss at next meeting.

1) On the following project no references appear which should be impossible as it is necessary to add the references for a review findings before completing the CERQual assessment
![image](https://user-images.githubusercontent.com/72507850/223161400-2fc475d7-0b15-4826-9b4b-4d92c50c4801.png)

2) On the following project no findings appear. Did they not create findings or is this a glitch?
![image](https://user-images.githubusercontent.com/72507850/223161764-19dc8c11-5684-4533-834f-9d1650eeca54.png)

3) The following project only has one finding and it is finding #3. What about finding #1 and #2. Seems odd that only #3 appears.
![image](https://user-images.githubusercontent.com/72507850/223162468-f81ecbc9-de01-4b49-aad5-cbd10583974c.png)

4) the following looks both incomplete and also quantitative rather than qualitative, but no email address provided
![image](https://user-images.githubusercontent.com/72507850/223163704-82ae9df7-0186-43d1-859e-0df311991c68.png)

5) The following doesn't have a proper title and very little info. Is this just the authors who have published it in a very incomplete state or is there a display error?
![image](https://user-images.githubusercontent.com/72507850/223164355-dd5411c4-d5f1-4907-8e5b-5335e10af422.png)

**Comment by damian-garrido** [comment]
hi @MJWainwright 
i was checking one by one and find that most of them was incompleted not for the information, but, for the process on the publish.
i'm not 100% sure, but, i thnk the issue probably is when a user click on publish and close the window and change the view.
for example, in the case of the references, most of the projects have references, but was not available, so, is not possible to display on the Browser section.
if the user republish the project and await until the process is done, then the references will be visibles.
on other case, for example in the "Factors influencing women's participation in personalized screening programs. A framework synthesis of qualitative research" SOQ, they have a mess with the Characteristics of Studies table columns name, also, for some reason, they write over the author name with responses, or maybe was related to the software they use to open the template data. i opened the themplate with openoffice and the data seems to be correctly
in this case in particular, is possible to fix re-downloading the template and fixing the data correctly.
if you want we can have a meeting for talk about this issue.

**Comment by MJWainwright** [comment]
@damian-garrido . I emailed all the authors but heard nothing back. I think we should intervene to "clean-up" this page. let's discuss at our next meeting

**Comment by MJWainwright** [comment]
@damian-garrido . Let's please go ahead and clean-up this page. Currently only two projects are appearing correctly. I've noted before whether the projects should be re-published according to the level of visibility chosen by the authors OR whether the project should be unpublished entirely.

![image](https://github.com/epistemonikos/isoq/assets/72507850/16366fc7-821c-4d71-8c50-2d0f889853ff)

**Comment by MJWainwright** [comment]
@damian-garrido Any chance you can get to this before you go on holiday?
