### ISSUE TITLE
Add/Edit reference functionality not working on Worksheet

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#164]
Hi Damian, a user discoverd the add/edit reference functionality is not working on the Evidence Profile table in the GRADE-CERQual assessment worksheet. I have confirmed that indeed it is not working.

1. on iSoQ page I assigned two references to a finding
2. on Assessment Worksheet page I clicked "view or edit references" and selected a third reference. It looks as though it has been selected
![image](https://user-images.githubusercontent.com/72507850/231797550-f37f74e9-b62f-4919-9f41-71c7a5527c24.png)
![image](https://user-images.githubusercontent.com/72507850/231797666-80e6d216-791f-4619-ab39-c77004cc271f.png)
2. but when I clicked "ok" and the modal closed, the reference column on the evidence profile table still said only 2 references even though all three are selected
![image](https://user-images.githubusercontent.com/72507850/231798145-c0ebcb89-291b-4511-af7c-c1b68c480d8a.png)
3. when I clicked "view or edit references" again I can see the three references are selected
4. When I navigated back to the iSoQ page using the "return to iSoQ table" link it also shows only two references
![image](https://user-images.githubusercontent.com/72507850/231798503-c0935e44-7f3c-422b-9e0d-b1327b19fea3.png)
5. when I clicked on "complete grade-cerqual assessment" and went back to "view or edit references", the third reference I had selected is no longer selected. 
![image](https://user-images.githubusercontent.com/72507850/231798776-f4ba010e-5656-4982-8f61-55b02d07a61b.png)

**Comment by damian-garrido** [comment]
@MJWainwright an update was published on the test server, could you check please!

**Comment by MJWainwright** [comment]
@damian-garrido. Checked, looks good, please publish to production server. Let me know when it is done and I will test it there, confirm all is good, and then close this ticket. Thanks!

**Comment by damian-garrido** [comment]
was published on the production server
