### ISSUE TITLE
Add a "What's new" tab/pop-up on the homepage to inform users of changes

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#171]
So that users know of new features, fixes and improvements we could have a little verticle tab somewhere on the screen that says "what's new" and if users click it it opens and has information about recently added or improved features. I'd like it if you could propose some different design ideas for this so we can choose

**Comment by MJWainwright** [comment]
@damian-garrido Could you please rate this enhancement as either S, M or L? thanks!

**Comment by damian-garrido** [comment]
@MJWainwright i was working on this, but i have some issues with the menu
so, i made some changes, primarily moving the "My Workspace" under the expansible menu that appear under the username.

![Screenshot from 2024-04-05 16-07-42](https://github.com/epistemonikos/isoq/assets/25389333/642d78f0-07f5-415d-8b1f-45ff1d4e39d6)

if i restore the "My Workspace" and maintain the "What's New" this will overlap the "interactive Summary of Qualitative Findings" text.

![Screenshot from 2024-04-05 16-11-07](https://github.com/epistemonikos/isoq/assets/25389333/57a0598d-ff97-4a57-b204-fe5f5cdc31a3)

this affect primarily resolutions under 1024x768, greater than this, will no be affected.
what do you think about this change?

**Comment by damian-garrido** [comment]
@MJWainwright i made that you suggest, seems works perfect! what do you think?

[Screencast from 2024-04-17 11-12-06.webm](https://github.com/epistemonikos/isoq/assets/25389333/0f7ed0bd-9291-4f0d-a0a0-3dd726e9d60f)

**Comment by MJWainwright** [comment]
@damian-garrido This looks great!

**Comment by MJWainwright** [comment]
@damian-garrido Will we test the linked "google doc" function for the What's new page? The idea is that I will have a Google Doc that I keep updating right? And then that automatically is reflected in the What's new page. Is that right?

**Comment by MJWainwright** [comment]
@damian-garrido . See comment above. It would be great to have this up and running in order to advertise some of the nice enhancements coming up (e.g. re-organisation of My Data section). I'd like to test the whole process using the google doc.

**Comment by MJWainwright** [comment]
@damian-garrido How close are we with this one? Would be great to test out the google form link to this page

**Comment by MJWainwright** [comment]
@damian-garrido . Looks good on the Test server. Is all the text that's there now editable? Can you explain to me how to edit it? Thanks!

**Comment by damian-garrido** [comment]
just need to edit the file called "WhatsNew.vue" under the folder called "src", then add the content that you need to appear.

to add a paragraph you need to add the <p></p> tag for example:
<p>this is a paragraph</p>

to add a list you need to use the <ol></ol> for an ordered list and <ul></ul> for an unordered list, and for each item in those list you need to use <li></li> for example:

<ol>
<li>item 1</li>
<li>item 2</li>
<ol>
this will generate:

1. item 1
2. item 2

and the same for unordered list using <ul> and </ul> instead of <ol>and </ol> to generate the following

- item 1
- item 2


we can have a small meeting for explain with more details.
let me know

**Comment by MJWainwright** [comment]
@damian-garrido . Ok, yes I will need some training on this from you. My schedule this week is a bit full. Let's schedule a time at our meeting on Thursday.

**Comment by damian-garrido** [comment]
perfect!

**Comment by MJWainwright** [comment]
@damian-garrido  I've logged in to github to test this but I can't seem to find the WhatsNew.vue page. I tried following your path above (e.g. SRC - components) but it is not there. When I searched feature/171 it seems to locate something but I still don't see WhatsNew.vue. Can you help me find it again? Thanks!

**Comment by damian-garrido** [comment]
@MJWainwright the page will be available under src/components folder, under the branch develop, here a screenshot of the page, let me know if you still facing the problem finding this one.

![image](https://github.com/user-attachments/assets/69ec9669-5ffb-4d75-9297-ad8437daa249)

**Comment by MJWainwright** [comment]
@damian-garrido Got it! I was forgetting to select "develop" as the branch. I've added some text, can you see if I did it right?

**Comment by damian-garrido** [comment]
@MJWainwright i saw your changes but i fix them
please, check again the page to see whats was the changes.
here you can check what the changes was https://github.com/epistemonikos/isoq/commit/cd53815e720bf3a46d6f609a6a7f988d40808082
let me know anything

**Comment by MJWainwright** [comment]
@damian-garrido aha! I see what I did wrong. Can you publish the What's new page to the test server so I can see what it looks like?

**Comment by damian-garrido** [comment]
@MJWainwright i will do and let you know

**Comment by damian-garrido** [comment]
@MJWainwright sorry for the delay, today i could deploy your changes, let me know anything

**Comment by MJWainwright** [comment]
@damian-garrido checked on test server, all good and ready to publish to production server

**Comment by damian-garrido** [comment]
@MJWainwright deployed!

**Comment by MJWainwright** [comment]
@damian-garrido looks good on production server, thanks!
