### ISSUE TITLE
Added email addresses in "invite" don't disappear in copied project

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#175]
1. I created a project
2. I started adding email addresses to "invite" others to the project, but I realised I did not want to share it, but rather a copy of it.
3. So I did not complete the action of inviting people and went back to the My Workspace page and duplicated the project
4. when I click "invite" of the copied project all those email addresses I had put in the field are still there. However, they do not appear in the original project.

**Comment by damian-garrido** [comment]
hi!
i have a doubt,
at step two, you send the invitations or not?
because in the step four you mention that are all the email addresses but i understand you dont invite them.
im confused

**Comment by MJWainwright** [comment]
That's right, at step 2 I didn't invite, I typed in three email addresses, then I realised I actually didn't want to share this project so I closed the modal.

**Comment by damian-garrido** [comment]
i fixed this issue, could you check this on the test server please!
saludos

**Comment by MJWainwright** [comment]
It looks good on the duplicated project, but noticed that the addresses also "stick" in the original project until you close the project and open it again. Can you test it on your side. Create a new project, add some email addresses but don't click "add", just click  "close". When you then click invite again those email addresses are still there. But you can delete them at least. Do you think this is the way it should be? Or should the email addresses be wiped when the user clicks "close" before they click "add"?

**Comment by MJWainwright** [comment]
@damian-garrido This seems to be fixed so please go ahead and publish to the production server

**Comment by MJWainwright** [comment]
@damian-garrido Checked on production server. All good, thanks!
