### ISSUE TITLE
Add an option to sign-up to newsletter when user creates an account

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#179]
We have decided to disseminate updates and new features in iSoQ via the GRADE-CERQual newsletter. Therefore, it would be great if we could ask users to sign-up to the newsletter when they create an iSoQ account.

**Comment by damian-garrido** [comment]
what about the existed users?
may be i could add the same question in the password section, what do you think?
i propose this space because we dont have a section for the user

**Comment by MJWainwright** [comment]
@damian-garrido I've already emailed all existing users to ask them to sign-up to the newsletter, but perhaps it is good to remind users that they can sign-up in case they ignored that when they created the account. So you're right the question could be in both sections (create an account, and sign-in) The link for the mailing list form is: https://docs.google.com/forms/d/e/1FAIpQLSctGa_fZ0A9XclGWcT2PHxP_I2FD0k4ylOeW93G8w18VRP11g/viewform

**Comment by damian-garrido** [comment]
@MJWainwright 
i'm start to working on the subscription invitations, what do you think?
maybe it's necessary to change the message, but, i think this could be a good place for promote the newsletter.

![image](https://github.com/epistemonikos/isoq/assets/25389333/48ac952f-ee5b-4490-b929-895ec43236aa)

![image](https://github.com/epistemonikos/isoq/assets/25389333/a77f6247-f36a-4b29-a312-3ec6f02868fb)

the link would open a new tab for the newsletter formulare.
what do you think?

**Comment by MJWainwright** [comment]
@damian-garrido Thanks for these initial options! A couple things:

- I think we said we would prompt joining the newsletter on the Create Account page and on the Change my password password, but not on the login page. Do you think it's a good idea to have it on the login page as well?
- Could we make it more interactive? For example, someone creates an account and when they click "create" a pop-up appears which asks them "Would you like to receive the GRADE-CERQual newsletter?" and then makes them click "yes" or "no". If they click "yes" then that would open up the form in a separate tab. What do you think of something like that?

**Comment by damian-garrido** [comment]
hi @MJWainwright 

* i thinked it should be on login page, but, i will remove from here, no problem. having an "invitation" in the login will reinforce a user to being subscribed to the newsletter, but i'm not sure if this will be a good or a bad idea
* this popup will appear when the user arrive to the workspace the first time? what happens when a user click on "no" and then want to subscribe, in which place the user will be find this option again? in About page? Help page?

**Comment by MJWainwright** [comment]
@damian-garrido

**Login page for existing users** - Yes, let's keep what you have above. It's just text and a link to the sign-up form
**Create account page** - can we please have a pop up that appear after the user clicks "create" account where they have to click either "yes" or "no" to receiving the newsletter. This way they cannot ignore it, they have to say yes or no. The way you have it they can just ignore that sentence and click "create account"
![image](https://github.com/epistemonikos/isoq/assets/72507850/d92b5eff-69ff-4961-a08d-a92cb4ba00c4)

**Change password page:** Same principle as the create account page. When the user clicks "save" a little pop-up appears and they have to click either YES or NO.

**Comment by damian-garrido** [comment]
question, in the change password page, every time a user change their password the modal will appear?

**Comment by MJWainwright** [comment]
@damian-garrido Apologies for loosing sight of this ticket and your question. Yes, I think so. That shouldn't be too annoying for users because I doubt they are changing their passwords frequently

**Comment by MJWainwright** [comment]
@damian-garrido I have checked the test server and I can't see anything about the newsletter sign-up on any of the pages. Did you forget to publish it to the test server? As a reminder:

- Sign in - fixed text at the bottom like you had above
- Create an account - the pop-up modal function as described above
- Change password - the pop-up modal function as described above

**Comment by damian-garrido** [comment]
@MJWainwright next week i'm going to publish this to the test server, i'll let you know

**Comment by damian-garrido** [comment]
@MJWainwright i publish this on the test server.
i couldn't do this before, could you check this when you have some time, please!

**Comment by MJWainwright** [comment]
![image](https://github.com/epistemonikos/isoq/assets/72507850/d95141f9-034f-43ac-84d5-8b8b127fa19f)

@damian-garrido 
Would it be possible to replace the "yes I want to subscribe" with just centered YES and NO buttons below the question. The YES button takes users to the form, the NO button closes the modal.

Can you please replace  the question with:
**Would you like to subscibe to the GRADE-CERQual mailing list? You will receive three newsletters a year that include the latest news about iSoQ.** 

Replace the text with:

**Comment by MJWainwright** [comment]
For the "login" newsletter prompt:

![image](https://github.com/epistemonikos/isoq/assets/72507850/4736a938-0f3c-4bde-ac97-53126b905756)

Can you please replace the text with:
**Would you like to subscribe to the GRADE-CERQual mailing list?** **Yes, I want to subscribe!**

**Comment by MJWainwright** [comment]
For the "create account" newsletter prompt

@damian-garrido . This isn't right. What we want here is the same thing as the "change password" action. When the user clicks "create account" a pop-up should appear with the same thing as I wrote above for the change password section. If the user clicks "YES" the account is created and iSoQ navigates to My Workspace but the user is directed to a new window with the mailing list sign-up form. If the user clicks "NO" then the modal closes, the account is created and they are taken to the MyWorkspace page.

**Comment by damian-garrido** [comment]
hi @MJWainwright 
could you check please, i made the change that you request.
let me know anything!

**Comment by MJWainwright** [comment]
@damian-garrido This looks and works great now! You can publish to the production server!

**Comment by damian-garrido** [comment]
Hi @MJWainwright !
this update was published on production server, could you check please!

**Comment by MJWainwright** [comment]
@damian-garrido Checked. All good
