### ISSUE TITLE
Make the edit buttons visible without having to scroll along a row

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#207]
A user has brought up a usability issue. Right now a user always has to scroll all the way right along a row in a table (My Data section) in order to click the edit button. This particular user had to add information for each study so it was annoying to have to scroll right row by row just to be able to click on the edit button. Can we make it so that the edit button remains visible (i.e. frozen)?

**Comment by MJWainwright** [comment]
@damian-garrido I think we discussed this option but the decision was to go with have the edit and delete button fixed in a kind of "frozen" column that is always visible. Because we don't know how many columns people will have, perhaps we could move the buttons to the first column on the left, rather than the last on the right. So you would have the edit and delete buttons, then the authors/year column, and then the data columns. As the user scrolls along, the edit/delete buttons stay visible. I don't really like the hovering and then appear option you show in the video. I think it can be a bit annoying for users. So if you hover, the buttons block information from view, such as the author and the year, which I think would be frustrating.

**Comment by damian-garrido** [comment]
@MJWainwright ok, i will move the edition buttons to the first column and freeze this when the user scroll to the right.

**Comment by damian-garrido** [comment]
@MJWainwright what do you think?

[Screencast from 2024-03-14 08-39-34.webm](https://github.com/epistemonikos/isoq/assets/25389333/a8e4167d-c02a-4713-9f7f-cca8195018b2)

**Comment by MJWainwright** [comment]
@damian-garrido . I like it! Makes me wonder as well whether it's useful to also freeze the author/year column. I would find it useful to always be able to see which study I am looking at, what do you think? Or we get some user feedback on that first?

**Comment by damian-garrido** [comment]
@MJWainwright unfortunately, make two columns sticky at the same time is not possible, one will be overlapped, the first one.
but, i could put the buttons under the author/year column, what do you think?

**Comment by MJWainwright** [comment]
@damian-garrido . No let's keep it how you had it in the video above. Thanks!

**Comment by MJWainwright** [comment]
@damian-garrido Can this be implemented? See my response below. I don't see it on the test server. Thanks!

**Comment by MJWainwright** [comment]
@damian-garrido It looks good, can be published to production server. However, for some reason the iSoq test server is showing the old design of the MyData section. I cleared cache and tried a couple times.
![image](https://github.com/epistemonikos/isoq/assets/72507850/2de4a8f9-8a02-4be6-8cda-ea8e5c968c21)

**Comment by damian-garrido** [comment]
hi @MJWainwright 
yes, don't worry about this, its because they are two separated branches.
when i publish this to the production server, both branches will be merge and display all correctly.
but before, i'm going to do in the test.

**Comment by damian-garrido** [comment]
@MJWainwright now are merged and will have the both implementations

**Comment by MJWainwright** [comment]
@damian-garrido Looks great! Can be published to production server

**Comment by damian-garrido** [comment]
@MJWainwright published!

**Comment by MJWainwright** [comment]
@damian-garrido . Checked on production server, all good!
