### ISSUE TITLE
Sizing of columns wrong in print/exported iSoQ table

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#208]
The width of the column for "CERQual assessment" is too big and the width of the column for the "summary of the review finding" is too small. This is both onscreen when you click "print/export" and when you view the PDF. The Word version is ok.

![image](https://github.com/epistemonikos/isoq/assets/72507850/203f6033-d929-432a-97a8-61517fb370b5)

**Comment by damian-garrido** [comment]
@MJWainwright published on the test server

**Comment by MJWainwright** [comment]
@damian-garrido checked. all good. Please publish to the production server
