### ISSUE TITLE
New references to add to "Guidance on Applying GRADE-CERQual" tab

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#212]
@damian-garrido We have new resources to add to the Guidance on Applying GRADE-CERQual tab on the iSoQ page. See image for placement.

![image](https://github.com/epistemonikos/isoq/assets/72507850/5b1ae536-0f37-4b3b-940c-fbfe525b5044)

1. Wainwright, M., Zahroh, R.I., Tunçalp, Ö., Booth, A., Bohren, M.A., Noyes, J., Cheng, W., Munthe-Kaas, H., & Lewin, S. The use of GRADE-CERQual in qualitative evidence synthesis: an evaluation of fidelity and reporting. Health Res Policy Sys 21, 77 (2023). https://doi.org/10.1186/s12961-023-00999-3.  [FULL TEXT](https://rdcu.be/dhKrV)
2. For more information on where GRADE-CERQual fits into the review process please see the [EPOC QES protocol and review template](https://zenodo.org/record/5973704#.ZEaQJ3bMLrd).
3. Watch the [Introduction to GRADE-CERQual videos](https://www.cerqual.org/grade-cerqual-videos/) here at your convenience

**Comment by damian-garrido** [comment]
@MJWainwright published on the test server

**Comment by MJWainwright** [comment]
@damian-garrido . Checked. all good. Please publish to production server
