### ISSUE TITLE
New text to add because people without a gmail account cannot use the tech issues form

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#213]
Please can you replace the text that is struck out with the text in yellow?

New text:
You need help?
...report your issues using this form
If you cannot access the form email us at isoq@epistemonikos.org

![image](https://github.com/epistemonikos/isoq/assets/72507850/ac9cf796-7fbb-45a3-8260-eae973b745fb)

**Comment by damian-garrido** [comment]
@MJWainwright published on the test server

**Comment by MJWainwright** [comment]
@damian-garrido . Can you please delete the space between the two sentences?

![image](https://github.com/epistemonikos/isoq/assets/72507850/746df378-b44b-464f-871a-3a9ed593da67)

**Comment by damian-garrido** [comment]
@MJWainwright fixed and published
