### ISSUE TITLE
filter name not visible when selecting it

### ISSUE THREAD

**Issue by javierapena** [epistemonikos/isoq#217]
![Captura de Pantalla 2023-09-28 a la(s) 11 43 02](https://github.com/epistemonikos/isoq/assets/145139545/c53c1f6a-717e-4666-b94b-3de1560bdefd)

**Comment by damian-garrido** [comment]
@javierapena published on test server

**Comment by MJWainwright** [comment]
@damian-garrido Checked on test server, all good. Can go to production

**Comment by MJWainwright** [comment]
@damian-garrido Checked on production server. All good
