### ISSUE TITLE
Make each step of the MyData section expandable and collapsable

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#223]
I need to sketch out a design for this but wanted to post this enhancement so I don't forget about it.

**Comment by MJWainwright** [comment]
@damian-garrido 

Thanks for the videos with the three options.I think the best options is tabs example 2. I think it's useful that the tabs are always in view on the left, which avoids users having to scroll up and down to minimize and/or maximise steps. A few additional questions come to mind though:

- currently users reach the bottom of the page and click "continue to iSoQ" to move on to the iSoQ table. How would it work with the tabs version? Would there be a "continue to step 2" at the bottom of the step 1 open tab, then a "continue to step 3" at the bottom of the step 2 open tab,etc, until you get to the "continue to iSoQ" on the Step 4 open tab? Would that force users to have to click a bunch of times to reach the iSoQ page if they were not aware that they could simply click on the "iSoQ" horizontal tab which become active once references are added? On one hand it does remind users that they completing optional steps 2-4 is highly encouraged, on the other hand in may be annoying. What are your thoughts?
- The other question is what rules will iSoQ follow when users open up an existing iSoQ project:For example:
   - if they have already done step 1 then maybe displaying step 1 tab shouldn't be the default. But what should be the default? Maybe if iSoQ can detect that some content was added to inclusion and exclusion criteria, then the default should be displaying Step 3. While step 2 is important, I think Step 3 and Step 4 are more so. Also, users are warned that content is missing from these steps when they get to the worksheet pages. Or, perhaps iSoQ can remember which step of the MyData section was last worked on and display that next time someone logs in? (i.e. people can pick up where they left off). What do you think? What are our options and what in your view would make the most sense?

**Comment by damian-garrido** [comment]
hi @MJWainwright 
* i think that the implementation of a button at the end of the step is a very good option, not everybody maybe notice that the steps are tabs. also, for the user is not necessary follow the scheme of step-by-step, they could jump using the tabs when they notice there is a tab for every step. 
i'm going to make visual improvements in this part that could help to the user to understand easelly the tabs concepts in this part.
* i understand your concern about this, i think its a good idea to send a user to the step 2, as default, if the user dont have inclusion or exclusion criteria and if the user has both, send to the step 3 as default and send to the step four if the user has at least a table in the step 3.

now i have a doubt in case a user has all the content filled, what will be the step for default?

**Comment by MJWainwright** [comment]
@damian-garrido . This direction sounds good Damián I think if they have all the content filled (e.g. not necessarily every cell but they have started a table), then could we make the default the last page the user was visualising before they logged-out/closed the program? Because we won't know if a table is actually finished or not. It may have content in every cell, but that content is unfinished. If it's not possible to send the user back to where they left off next time to open the project from the Workspace, then maybe let the default be the iSoQ page/tab, so long as there is some content in each of the four steps in the MyData section. What do you think?

**Comment by damian-garrido** [comment]
@MJWainwright what do you think of showing the list of references instead of open a new window? i'm asking because now we will show every step in an independent view.
let me know!

![image](https://github.com/epistemonikos/isoq/assets/25389333/6bf61561-98fb-4bc0-bcff-bcf282cf592d)

**Comment by MJWainwright** [comment]
@damian-garrido I like this idea. But can you make the following changes? (I also noticed the word "review" is missing before "findings" in the name of the column. This is important so that users don't get confused between findings from individual studies, and findings from the review).

![image](https://github.com/epistemonikos/isoq/assets/72507850/29fd0b13-1207-4646-b83f-bcfd2e1560eb)

**Comment by damian-garrido** [comment]
@MJWainwright working on this issue, i have a question related to the references.
if i complete all the steps of Assessment Worksheet, and then remove all my references, i understand that the Characteristics of Studies, Methodological Assessments and Extracted Data tables should be removed, but, what about the responses on WorkSheet, should i remove the responses of this section or not?

**Comment by damian-garrido** [comment]
@MJWainwright can you check this functionality (steps as tabs) available on the test server, please.

**Comment by damian-garrido** [comment]
@MJWainwright yes, we have an option to delete all the references, now appear on the modal when you see all the references, at the end, there is a button that allow to you delete all the references.

**Comment by MJWainwright** [comment]
@damian-garrido Could you also make a small edit for me on the modal for deleting a single reference? I noticed just now that it says "finding" in two places, instead of "review finding". Can you please make this replacement in the two places? Thanks!

![image](https://github.com/epistemonikos/isoq/assets/72507850/3f469c53-2a16-4122-9b20-bed08d361de7)

**Comment by damian-garrido** [comment]
@MJWainwright what do you think if i add a red color to the text when a user try to delete all the references.

![episte lo_8090_workspace_e8f7d01037d98af5_isoqf_660ac996398b92c3f7a581c8](https://github.com/epistemonikos/isoq/assets/25389333/5d5ad9e8-56fa-4f1b-9d2a-0f4ec910f31b)

**Comment by MJWainwright** [comment]
@damian-garrido Yes this is good, but I noticed I made a small mistake. It should say Summary of **Qualitative** Findings Table. Can you please add the word "qualitative". I like the red colour and the bold on the question. Thanks!:)

**Comment by damian-garrido** [comment]
@javierapena @MJWainwright 
I made the changes that Megan suggested, could you please verify them?

**Comment by MJWainwright** [comment]
@damian-garrido Looks good! You can publish to the production server, thanks!

**Comment by MJWainwright** [comment]
@damian-garrido Checked on production server, all good! Thanks:)
