### ISSUE TITLE
Findings numbering not the same in iSoQ and Worksheet

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#228]
@damian-garrido. In Claire's project "Factors that influence the provision of enteral feeding for critically ill children in paediatric intensive care: a rapid qualitative evidence synthesis." the numbering of the findings is not correct in the Worksheet. 
She sent me this example. Finding 1 in the iSoQ table becomes Finding 2 in the Evidence Profile Table in Worksheets.

![iSoQ](https://github.com/epistemonikos/isoq/assets/72507850/0f1db3fe-3633-44cd-bad3-fab52e116a29)
![Evidence profile](https://github.com/epistemonikos/isoq/assets/72507850/aa403580-f435-4bd8-9d72-519158b50d3e)

**Comment by damian-garrido** [comment]
hi @MJWainwright and @javierapena 

i was working on several improvements and its include this issue.
could you check if this works on the test server?

if you use and old project, for fix this issue, for the moment, you need to open the "re-order your review findings button"
the next week i will work in a way that the user don't need to do anything.

if you create a new project and then create new findings, this will be works. also, if you, for example, create 3 findings and then delete one, and then click on one of them, the numbers will maintain the new order.

let me know if you have any issue or you couldn't test it

**Comment by damian-garrido** [comment]
hi @MJWainwright for the moment, the correct order for the findings will only affect to new projects, for old projects you could edit and save a finding or open the organization finding button and save, without moving any item and this will be generate the correct correlative numbering, i'm still working for detecting old project with incorrect correlative numbering

**Comment by MJWainwright** [comment]
@damian-garrido I tested this but it is still not working correctly

1. I created a new project
2. I added 4 findings
3. I looked at the GRADE-CERQual Assessment Worksheet for each of the findings and the numbering was correct
4. I deleted finding 2
5. I looked at the GRADE-CERQual Assessment Worksheet for each finding and the numbering was not updated, so it was incorrect. That is, finding #1 stayed Finding #2, but finding #2 says Finding #3 and finding #3 says Finding #4.

![image](https://github.com/epistemonikos/isoq/assets/72507850/76761f0a-910d-4cc8-8dc4-d43cbfb39ce2)

![image](https://github.com/epistemonikos/isoq/assets/72507850/2e04ba48-e3b4-4902-aadc-311b5a48bd87)

**Comment by damian-garrido** [comment]
oh no @MJWainwright 
im going to check again because i made the same steps.
gracias!

**Comment by damian-garrido** [comment]
hi @MJWainwright , i publish a patch for this issue.
try to clean your cache if you face the problem again.
saludos!

**Comment by MJWainwright** [comment]
@damian-garrido . Oh no! Damián some really weird things are happening now. Assigning the references to the finding changes the order of the findings.
ex:
- new project
- add three findings
- Assign the references to finding 1 - this causes finding 1 to change position and become finding 3

We don't want that to happen. They should be numbered in the order that they have been entered into iSoQ.

I think you need to work on this some more and keep testing it with Javiera. @javierapena can you please test this when damian comes back with another fix? The way it should work is:

- Findings are numbered in the order they are entered to iSoQ
- The numbering should be exactly the same in the worksheet (i.e. finding 1 in the iSoQ table is labelled finding 1 in the Worksheet).
- "Re-ordering review findings" is the only way to change order and these changes should be reflected in the Worksheets to
- If a user deletes a finding those that come after it will change - i.e. if I delete finding 2, finding 3 becomes finding 2, finding 4 becoes finding 3 etc.

Thanks!

**Comment by damian-garrido** [comment]
oh no @MJWainwright 
i check this on the test server and you are right! 
so, i test this behavior on my computer and i dont have this issue.

- i create a new project
- import references from pubmed (4)
- didnt create tables for assessments or characteristics
- create 3 findings (C, B, A)
- assign to C a single reference
- the list still in the same order (C, B,A), and also, when i access to the Worksheet, the numbers still in the right order.

so, im going to check if there are some issue when i re-build the software on the test server or there is a issue on the code.

**Comment by MJWainwright** [comment]
@damian-garrido any verdict? Did you find a problem with the code?

**Comment by damian-garrido** [comment]
hi @MJWainwright 
i was working and testing this the last week, on monday i ask to javiera to look and test this, she do some test and all was fine.  now is out of the office until 20 dic if i remember but camila will look and test this the next week.
from my side, i test and i don't see any problem, both, on the test server and also my local machine.
i think the error that you have was related to cache but i'm not 100% sure.

**Comment by MJWainwright** [comment]
@damian-garrido great, let's see what Camilo finds next week.

**Comment by MJWainwright** [comment]
fixed on production server
