### ISSUE TITLE
Excel template - year appearing in column C

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#237]
@damian-garrido this is the first time this has happened. When I download the Excel template and open it, "year" is appearing as its own column heading in column C. It should be part of column B. The references can still be imported but the author and year are in quotation marks. This is the first time I've seen this. I will send you the excel file by email. 

![image](https://github.com/epistemonikos/isoq/assets/72507850/fd6be2ff-6089-4352-a635-2bb259188300)

![image](https://github.com/epistemonikos/isoq/assets/72507850/87fc4930-9163-4448-99c0-ef247cc87829)

**Comment by damian-garrido** [comment]
hi @MJWainwright 
could you send me the RIS file that you use for this, i would like to thes the entire process.
thanks!

**Comment by MJWainwright** [comment]
@damian-garrido . I did the following:

- I imported 26 refs from an RIS file (will send you by email)
- I deleted the Dahlin 2006 study
- I added 3 studies from Pubmed: IDs: 37474226, 37137510, 36958741

Going back this morning I have noticed something else that is weird. When you click "view references" there appears "#undefined" one or more times in the column "related to finding(s)" for some of the studies but not all. I've not seen this before. 
![image](https://github.com/epistemonikos/isoq/assets/72507850/ea04ee86-705a-42be-9784-fca3503108c4)

**Comment by MJWainwright** [comment]
@damian-garrido were you able to reproduce the issue with the file I sent you and the steps detailed above?

**Comment by MJWainwright** [comment]
@damian-garrido I just met with a user who also had the same issue as above. I think our template is out of date somehow. It seems to be often showing the year in column C. This was not the case before. Could you please look into this again and see if something about the templates needs updating. Like I said, for me I never had a problem until recently. It's a showstopper issue.  Thanks!

**Comment by damian-garrido** [comment]
@javierapena  
i update the exportable, could you check if you are facing the problem!

**Comment by damian-garrido** [comment]
@MJWainwright 
could you check on the test server if you still facing the problem!

**Comment by MJWainwright** [comment]
@damian-garrido . Checked. It is now correct. Please publish to the production server, it's an important fix!

**Comment by damian-garrido** [comment]
@MJWainwright could you check if the update was successfully on the production server, please?

**Comment by MJWainwright** [comment]
@damian-garrido checked! all good. thanks:)
