### ISSUE TITLE
"Moderate confidence" Filter on iSoQ table not working correctly

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#238]
While testing fixes I discovered that when I selected "moderate confidence" as the filter it also showed me the findings assessed as "very low confidence". All the the other filters appeared to be working normally. 
![image](https://github.com/epistemonikos/isoq/assets/72507850/e52d839f-178e-4fe1-930d-543cd68ca30f)

**Comment by MJWainwright** [comment]
@damian-garrido any update on this one?

**Comment by MJWainwright** [comment]
@damian-garrido . Any progresso on fixing this little bug?

**Comment by damian-garrido** [comment]
sorry for the delay, it solved on 
 [https://github.com/epistemonikos/isoq/commit/f18d60ccadb821da373deac9d8e7a2e6a5f8cb25](this branch)

**Comment by MJWainwright** [comment]
@damian-garrido As we discovered yesterday the moderate confidence filter is now working, but the completed/not completed filters are not

**Comment by MJWainwright** [comment]
@damian-garrido . Update on this one?

**Comment by MJWainwright** [comment]
@damian-garrido checked on test server, all good. Can be published to production server

**Comment by MJWainwright** [comment]
@damian-garrido Checked on production server, all good!
