### ISSUE TITLE
Unable to login unless I refresh the page

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#240]
@damian-garrido . Both yesterday and today when I click login after entering my email and passwork from a new browser tab nothing happens. It's only if I refresh the login page that I can then re-enter my login information and the login button works. See the video below

https://github.com/epistemonikos/isoq/assets/72507850/7b7a00a6-78c2-47eb-9f5e-c63012d753cd

**Comment by damian-garrido** [comment]
@MJWainwright 
could you check if this happened with an incognito window?
i made a test on incognito and i don't have your issue. see the video below
try to clean up your cache and see if you still having this problem.
saludos

[Screencast from 2024-02-09 12-46-04.webm](https://github.com/epistemonikos/isoq/assets/25389333/cc7f4ec8-9a7e-45aa-af8c-421fede70e00)

**Comment by MJWainwright** [comment]
@damian-garrido . The problem seems to have stopped. I will close for now and if I encounter it again I will try opening in Incognito and clearing my cache. Thanks!
