### ISSUE TITLE
Change to logos on homepage

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#243]
@damian-garrido . Could you please add NTNU and HVL logos to the homepage below the others and also replace the NIPS logo with the new one. I will send them by email.

![image](https://github.com/epistemonikos/isoq/assets/72507850/fdbc18b6-c243-44d9-aefb-2ed52ad31d8a)

**Comment by damian-garrido** [comment]
@MJWainwright what do you think about this implementation?

![episte lo_8090_](https://github.com/epistemonikos/isoq/assets/25389333/5edc4bce-e808-4031-88c0-1c318e4611b4)

**Comment by MJWainwright** [comment]
@damian-garrido I feel the size of the logos is too large. The page looks unbalanced. All of the logos should be more or less the same size or smaller than the GRADE-CERQual logo at the top. Are you able to keep it as you had it but just add the other two logos below them?
Also, you'll have to use a white version of NTNU. If I didn't send you one, let me know. Thanks!

**Comment by damian-garrido** [comment]
@MJWainwright there is no white logo of NTNU, could you send me please.
the logos has all the same size in the height prop (80px) 
here another shoot with the size of 40px for every logo

![episte lo_8090_ (1)](https://github.com/epistemonikos/isoq/assets/25389333/29e1cb5a-f72b-4374-a560-5ee858ad7d06)

**Comment by MJWainwright** [comment]
@damian-garrido 
I've email Simon for a white NTNU logo. Can you make the epistemonikos foundation logo smaller. Even though the high is the same, the size of the text makes it look massive compared to the others, so the visual balance is a bit off. It also looks big vis-a-vis the GRADE-CERQual logo in the top left corner which is what I'm primarily comparing to.

**Comment by damian-garrido** [comment]
@MJWainwright i reduce the height of the epistemonikos logo to 30px, the others still in 40px

![episte lo_8090_ (3)](https://github.com/epistemonikos/isoq/assets/25389333/c4184aaf-5b89-4b10-8bbb-6466423830a8)

**Comment by MJWainwright** [comment]
@damian-garrido This looks much better! you'll have to see with the NTNU white logo. Maybe the N and U will be against the white shoes which won't be good. So maybe try putting NTNU first and the Western Norway University one second

**Comment by damian-garrido** [comment]
hola @MJWainwright!!
i made two version of the black strip, the first is 0.5 darkness and the other is 0.7, which one you prefer?

![episte lo_8090_ (7)](https://github.com/epistemonikos/isoq/assets/25389333/08db42c9-951f-45f7-975e-76fd24b96988)

![episte lo_8090_ (8)](https://github.com/epistemonikos/isoq/assets/25389333/f13dfb03-c996-4ace-a77c-1fd834c3b55d)

**Comment by MJWainwright** [comment]
@damian-garrido . The first one! Thanks:)

**Comment by damian-garrido** [comment]
@MJWainwright could you check this in the test server, please

**Comment by MJWainwright** [comment]
@damian-garrido Sorry one thing to change. You'll see earlier in my comments, I asked for the "first option" which was to have the NTNU logo first and the Western one second. Because of the size of the wording I think it will look better that way.

**Comment by damian-garrido** [comment]
@MJWainwright oh sorry! my mistake, i publish a new version. could you check please!

**Comment by MJWainwright** [comment]
@damian-garrido This looks good! Let's go with this. I haven't heard back from Simon yet about a white version of the NIPH logo.

**Comment by damian-garrido** [comment]
@MJWainwright  we can change this later :) 
i'm going to publish now!

**Comment by MJWainwright** [comment]
@damian-garrido . checked on production server. Good for now. The resolution of all the logos except for epistemonikos isn't great but maybe we can improve that later
