### ISSUE TITLE
Replace funded by info on the About page

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#244]
@damian-garrido Can you please replace the "How was the iSoQ tool funded?" section on the About page with the following please?

**How is the iSoQ tool funded?**
The development of the iSoQ tool is supported by funding from the Norwegian Institute of Public Health's Centre for Epidemic Interventions Research (CEIR). Additional funding for members of the development team is provided by the Western Norway University of Applied Sciences (HVL), the Norwegian University of Science and Technology (NTNU) and the Epistemonikos Foundation. 

![image](https://github.com/epistemonikos/isoq/assets/72507850/2885560c-78dd-412b-b2cb-295333825643)

**Comment by damian-garrido** [comment]
hi @MJWainwright
this change is available on the test server, let me know if this is ok and i will publish to the production server

**Comment by MJWainwright** [comment]
@damian-garrido the title is still the old title. The new title has "is" instead of "was" - How is the iSoQ tool funded?

**Comment by damian-garrido** [comment]
@MJWainwright replaced!

**Comment by MJWainwright** [comment]
@damian-garrido Looks good! Can be published to production server. Thanks!

**Comment by damian-garrido** [comment]
@MJWainwright published!

**Comment by MJWainwright** [comment]
@damian-garrido checked thanks!
