### ISSUE TITLE
Change password modal is missing the "repeat the password" box

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#255]
@damian-garrido To be consistent with the create account page can we please add a "repeat the password"box to the "change password" modal. It is currently not there so the user only enters their password once. 

![image](https://github.com/epistemonikos/isoq/assets/72507850/3f59b4ba-53cb-4926-b2c9-7c51de9c6aaa)

![image](https://github.com/epistemonikos/isoq/assets/72507850/a1cff7fa-6510-4932-8d3f-eeaee35fc0dd)

**Comment by damian-garrido** [comment]
@MJWainwright got it!

**Comment by MJWainwright** [comment]
@damian-garrido . Checked on test server, Can be published to production server

**Comment by MJWainwright** [comment]
@damian-garrido Checked on production server, all good
