### ISSUE TITLE
Reduce the size of the margins/padding on the whole iSoQ website

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#267]
@damian-garrido . Camilo tried out making the display of the webpages "full screen" and it worked really well. It seemed that all of the pages and tables were responsible to this except:

- inclusion and exclusion criteria tables (My Data)
- GRADE-CERQual component assessment and overall assessment modals (Worksheets)

We would like to go ahead and implement this so that we have a fullscreen mode across the whole website (currently we have rather large margins which limits the amount of space for visualising the information in iSoQ). We think this will help users a lot with visualising their tables and information in iSoQ. If it's not clear please discuss with Camilo as he tried it out "live" at today's meeting. 

Thanks!

**Comment by MJWainwright** [comment]
@damian-garrido . Was this done? Camilo tried it out "live" at a previous team meeting you weren't at and he said was straightforward. I think it looks like you've done it, but I'm not sure. Thanks for checking!

**Comment by MJWainwright** [comment]
@damian-garrido looks good on test server. Please publish to production server

**Comment by damian-garrido** [comment]
@MJWainwright the modal size was updated on the test server

**Comment by MJWainwright** [comment]
@damian-garrido Looking good, just reduce the size of the first column that has the radio buttons

**Comment by damian-garrido** [comment]
@MJWainwright i made un update of this, depending of the size of your screen, the size will be resize.

big screens
![image](https://github.com/user-attachments/assets/b996273b-7cae-4879-8b31-2b171660830a)

large screens
![image](https://github.com/user-attachments/assets/9462cb7f-53a2-4e54-aab4-6a930940d142)

medium screen
![image](https://github.com/user-attachments/assets/8696c301-19a4-47bd-a5f7-9c8bb2dda305)

**Comment by MJWainwright** [comment]
@damian-garrido . Very cool that it can adjust to screen size. But on mine it feels a bit too narrow. Could you make the first column just a bit wider?
![image](https://github.com/user-attachments/assets/455e426d-36c7-4009-bf44-d4dc5ba05231)

**Comment by MJWainwright** [comment]
@damian-garrido See comment above, I think the first column with the radio buttons needs to be a bit wider. It is too narrow now.

**Comment by damian-garrido** [comment]
@MJWainwright i made un update on this, could you check if this configuration works for your screen size

**Comment by MJWainwright** [comment]
@damian-garrido It looks like it is back to how it was, too big! See below more or less the size of the column. At the top, Evidence Profile will be on one line, and the name of the component, e.g. Methodological limitations, on the second line. 

![image](https://github.com/user-attachments/assets/a00dcd34-1804-43ce-a4bf-175e25187834)

**Comment by damian-garrido** [comment]
@MJWainwright the thing is, actually, the platform was build in a layer with 12 columns.
in this version i use 4 of the 12 columns and in the previous version i use 3.
i could a specific view for your resolution, but somebody with other resolution will have the same problem.
could you tell me wich size of your screen resolution is?

here some examples with the most populars screen resolutions:

4-columns
1024x768
![image](https://github.com/user-attachments/assets/cd409f18-f5fc-4900-8e14-faafd4f640c0)

1280x800
![image](https://github.com/user-attachments/assets/62c2a2a3-5fa9-4f88-9ce1-ddcd61d5309e)

1366x768
![image](https://github.com/user-attachments/assets/b32a00cf-b73e-4175-90d2-83830beed22b)

1440x900
![image](https://github.com/user-attachments/assets/60a20e21-4509-49df-8d30-5b0a23d9a91e)

3-columns
1027x768
![image](https://github.com/user-attachments/assets/f191150a-59c2-43a5-87b4-9f4fd72e2117)

1280x800 
![image](https://github.com/user-attachments/assets/2110c658-d09f-4b77-be99-2c56ff2e4cb5)

1366x768
![image](https://github.com/user-attachments/assets/8ac3f474-e4df-4712-be91-a17fb7496147)

1440x900
![image](https://github.com/user-attachments/assets/bab9bec5-637e-4c53-96a8-4f5cb3d579a2)

**Comment by MJWainwright** [comment]
@damian-garrido Ok I understand. Mine is 1366 X 768. Based on the images above, 3 columns at 1366 X 768 is the best.

**Comment by damian-garrido** [comment]
@MJWainwright the change was deployed on the test server, could you check?

**Comment by MJWainwright** [comment]
@damian-garrido Looks good on test server, can go to production. Thanks Damián!

**Comment by damian-garrido** [comment]
@MJWainwright published

**Comment by MJWainwright** [comment]
@damian-garrido checked on production server, looks good! thanks
