### ISSUE TITLE
Link to my data section in worksheet needs to take user to correct tab

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#270]
@javierapena Since we reorganized the MyData page, the links to the page need to be updated so that they take people to specific tab if possible. Could you please go through and note all the places where this needs to happen and liaise with Damián? Many of these links appear in the Evidence Profile models when data from any of the steps in MyData are missing, so I recommend creating a text project to find all the places where the link needs updating. There are also those on the main worksheet page for the first two tables. See example below:
![image](https://github.com/user-attachments/assets/5cb97050-dc48-4fba-bb7e-e4cfe59816f2)

Thanks!

**Comment by javierapena** [comment]
OK Megan! I'll go over it and coordinate with Damian

**Comment by damian-garrido** [comment]
fixed on branche https://github.com/epistemonikos/isoq/tree/bugfix/270-link-to-my-data

**Comment by MJWainwright** [comment]
@damian-garrido Checked on test server all good. Can publish to production server

**Comment by MJWainwright** [comment]
@damian-garrido I do not see the changes you showed me yesterday on the test server

**Comment by damian-garrido** [comment]
@MJWainwright published on test server

**Comment by MJWainwright** [comment]
@damian-garrido The links are working from the main Worksheet page, but they are not working from the Evidence Profile table modals. Check Methodological Limitations, Adequacy and Relevance. 
![image](https://github.com/user-attachments/assets/311fba39-8942-44c6-813e-22e87ce73949)

**Comment by damian-garrido** [comment]
@MJWainwright you are right and i fixed recently, could you check?

**Comment by MJWainwright** [comment]
@damian-garrido Checked on test server, all good. Can go to production server

**Comment by MJWainwright** [comment]
@damian-garrido Checked on production server, all good
