### ISSUE TITLE
Add section to Help tab

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#271]
@damian-garrido could you please add the following to the Help page before the section "GRADE-CERQual Webinars" (see image below).

**iSoQ Training Webinars**
- [Watch a presentation on iSoQ](https://vimeo.com/737300971)
- [Watch a demo of the iSoQ tool](https://vimeo.com/738892529)
- [Access Cochrane Training's session on iSoQ](https://training.cochrane.org/resource/how-the-isoq-tool-can-help-you-apply-grade-cerqual-in-your-qes)

![image](https://github.com/user-attachments/assets/300abf44-9c1f-4ec8-b915-73ec5cf86e5c)

**Comment by MJWainwright** [comment]
@damian-garrido did you publish to the test server? I don't see it and I cleared my cache

**Comment by damian-garrido** [comment]
@MJWainwright not yet because now is published the version for the publishing validations, when we check and test the other one i could change to this version for your checking.

**Comment by MJWainwright** [comment]
@damian-garrido . Checked on test server, all good. Please publish to production server.
