### ISSUE TITLE
Content from imported tables disappearing

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#30]
A user imported her tables successfull and everything looked normal when she added one review finding and started working on the assessment worksheet. But then she added two new findings and immediately noticed both in MyData and in the Worksheets that the tables were suddenly messed up - there was missing data in some columns where there had previously been data, in worksheets it showed the headings but not the studies or the data. I instructed the user to re-import the two tables. When she did so the problem resolved. However, what was the cause of the glitch with the tables?

**Comment by MJWainwright** [comment]
This issue continues:
"Unfortunately, it seems some bugs continue. I added 2 more findings and their references this morning (#4 and #5 in the screenshots) and it did that thing again of removing data from the tables- both in the characteristics of studies and the methodological limitations tables (and both on the 'My data' page and on the CERQUAL assessment page for the specific finding and associated references). I've taken some screenshots FYI."

**Comment by damian-garrido** [comment]
i think this issue was fixed, doesnt?

**Comment by MJWainwright** [comment]
Yes, it was fixed!
