### ISSUE TITLE
clone a project

### ISSUE THREAD

**Issue by damian-garrido** [epistemonikos/isoq#36]
ability to duplicate a whole project, this means references, review findings, tables but not shared people.

**Comment by damian-garrido** [comment]
hey @MJWainwright 
i made available this feature on test server, can you check this please!
one thing to define is if a user can clone a shared project or only can clone his own projects.

**Comment by MJWainwright** [comment]
hey @damian-garrido 

I tried to clone and this message appears: The project is still copying information, please dont change or refresh this page until this warning dissapear

Firstly a correction is needed, it should say:  "dissappears"

Secondly it's not clear to me what is meant by "change", do you mean navigate away from this page? I've waited 5 mins so far and the message hasn't dissappeared, so how long should it take? (we shoulds say in brackets how long this might take) What can I do in the meantime in iSoQ?

**Comment by MJWainwright** [comment]
I navigated away from the page into another iSoQ project, and then came back to My Workspaces and the cloned project was there. So perhaps the message will not disappear on its own?

As far as your question about whether "a user can clone a shared project or only can clone his own projects." This is a good question! the easiest way to address this that would not involve changes to the interface requiring new help videos would be to do the followinging:

Any user given the rights to "can view and edit" can:
- clone a project
AND
- invite other users to a project

A user given rights to "can view" only cannot clone or invite others to a project.
Currently we only let the creator of a project invite members to the project and this is a bit restrictive.

**Comment by MJWainwright** [comment]
Also, it's easy to accidentally click on the duplicate button by accident when really you want to click on another button (like share). So perhaps we could have a modal appear when the use clicks "duplicate" that says?

Do you want to duplicate (create a copy) of this project? (this copy will only be available to you). YES CANCEL

**Comment by damian-garrido** [comment]
> hey @damian-garrido
> 
> I tried to clone and this message appears: The project is still copying information, please dont change or refresh this page until this warning dissapear
> 
> Firstly a correction is needed, it should say: "dissappears"
> 
> Secondly it's not clear to me what is meant by "change", do you mean navigate away from this page? I've waited 5 mins so far and the message hasn't dissappeared, so how long should it take? (we shoulds say in brackets how long this might take) What can I do in the meantime in iSoQ?

@MJWainwright, thanks for the translation error :P

"change" mean click on another link, because this will be stop the cloning action. you can click on a project but this need to be opened in a new window.

for a slow conection i think this took like less a minute, im gonna check why this took to much time for you.

**Comment by damian-garrido** [comment]
@MJWainwright im going to close this tickect because was separated into small issues
