### ISSUE TITLE
clone project

### ISSUE THREAD

**Issue by damian-garrido** [epistemonikos/isoq#42]
if you are the owner or a user with "view/edit" permission can clone a project

**Comment by MJWainwright** [comment]
Damian, could you create a project on the test site, share it with me and give me editing rights? That way I can check if I am able to clone a project that I didn't create but for which I have "view and edit" permission. Thanks!!

**Comment by MJWainwright** [comment]
Hi Damian, I received an email about both invited projects but something weird is happening. For the project "testing Duplicate a Project with megan" I clicked on link from my email and it took me to the My Data page. However, when I navigate back to My Workspace this project does not appear in my list! (very weird!)

**Comment by MJWainwright** [comment]
However, with the second project "testing Duplicate a Project with megan (view/writte)" I could duplicate the project, so that's all good!

**Comment by MJWainwright** [comment]
Ah, however, I am not able to "share", so this is a problem. If I am given the right to edit and I duplicate the project, then I have to be able to access all the same functions as I would have if I created the project from scratch. This includes "share"

**Comment by MJWainwright** [comment]
Ok, I just received your share and it now appears in My Workspace. It all looks normal.
