### ISSUE TITLE
open a modal when a user click on clone project icon

### ISSUE THREAD

**Issue by damian-garrido** [epistemonikos/isoq#43]

**Comment by MJWainwright** [comment]
![image](https://user-images.githubusercontent.com/72507850/103784649-1d97b300-5032-11eb-9391-e4e86eb35a45.png)

We need to standardize the language. The tooltip for the button is "duplicate" not "clone". So please change the message to:

Duplicate a project

Click on the "duplicate" button to start making a copy of the project "[title of the project]". The content of the duplicate will be identical to the original but it will not be shared with other users automatically. Use the "share" button to share the duplicated project.

Close   Duplicate

**Comment by MJWainwright** [comment]
![image](https://user-images.githubusercontent.com/72507850/103785963-bc70df00-5033-11eb-9c1e-ef573107aede.png)

This worked quickly. But please change the text to:

**Duplicate complete. You can now close this modal.**

**Comment by damian-garrido** [comment]
@MJWainwright the corrections of this issue are deployed on the test server

**Comment by MJWainwright** [comment]
Checked. All good! Thanks:)
