### ISSUE TITLE
Import table error (data appears on additional row)

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#47]
Hiya Damián! I reproduced an error Claire found and shared the project with you "Reproducing Claire's Error". I am going to share you the Excel file that I imported via email. You will see in the characteristics of studies table when you scroll down to the Hutt et al. 2010 study that below that row is an extra row without a study in the first column. I don't know why this extra row is appearing, or how to delete it.

**Comment by damian-garrido** [comment]
@MJWainwright 
i made an update fixing this issue on the test server.
the problems its related to the break line in some cases when the user use alt+enter for start a new line in a single row.
i think now its support this kind of data.
can you test this creating a csv with some content and the content will need to contains this kind of break line content.

**Comment by MJWainwright** [comment]
Checked. All good! I did not find the error again. I did the test in project Test January 8 2021 that I shared with you. You can see below I did the breaklines:
![image](https://user-images.githubusercontent.com/72507850/104021766-41383600-51b7-11eb-9e0f-85fa405c0768.png)

**Comment by damian-garrido** [comment]
excelente!

**Comment by MJWainwright** [comment]
Damián can you do an update on the production server so this issue is fixed there? So that our users working on reviews with deadlines can keep working? Thanks!
