### ISSUE TITLE
Clarification request - forgot password function activated or not?

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#48]
Hi Damian,

Just a question. Claire found that she could not use the "forgot your password" function (i.e. it doesn't appear to be enabled). I assume that is because we are still on this limited release stage, but I just wanted to check with you. can the 30 or so users who currently have accounts that we made for them (realworld user testing), use the function "forgot your password"?

Thanks!

**Comment by damian-garrido** [comment]
@MJWainwright now its enabled on test server

**Comment by MJWainwright** [comment]
This works! But there is an error in the email message (says iSoQf not iSoQ) and grammatically needed a bit of editing. Please replace with:

A password recovery has been requested for your iSoQ account. Use the following link to create a new password http://isoqf-test.epistemonikos.org/accounts/new_password/megan@meganwainwrigh

**Comment by damian-garrido** [comment]
added the correction

**Comment by MJWainwright** [comment]
Apologies Damian, a signature is also missing, please add to the bottom of the email text:

Thanks!

GRADE-CERQual iSoQ - Powered by Epistemonikos

**Comment by MJWainwright** [comment]
This looks fixed on the production server so I am closing this ticket
