### ISSUE TITLE
Keep page stable when user clicks refresh

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#49]
Currently when the user clicks refresh on the MyData page the page refreshes and takes the user to the iSoQ page. Is there a way to make it so that when the user clicks refresh on any page that they remain on that page. Otherwise it is really jumpy

**Comment by ranazahroh** [comment]
Hi @damian-garrido, I have tested this and it still goes back to the iSoQ page when we refresh page on my data - would it be possible to revisit this? Thank you!

**Comment by ranazahroh** [comment]
Hi @damian-garrido - thank you for implementing the changes! Works perfectly now! I think this is ready to be pushed to the production server. We will suggest user clear the cache by pressing Shift + Ctrl + R together if this happens again.
