### ISSUE TITLE
Speech bubble missing from button

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#50]
![image](https://user-images.githubusercontent.com/72507850/103901725-6c585200-50f1-11eb-8eb2-a019befa7301.png)

The speech bubble icon should appear on both buttons "Edit GRADE-CERQual assessment"

**Comment by damian-garrido** [comment]
@MJWainwright its available now on the test server

**Comment by MJWainwright** [comment]
Checked. All good!
