### ISSUE TITLE
My Data tab is visible (inclusion/exclusion) when iSoQ is published 

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#52]
![image](https://user-images.githubusercontent.com/72507850/103903232-8bf07a00-50f3-11eb-9bbe-4cff180d6ddc.png)

The MyData tab should not be displayed at all when the project is published

**Comment by damian-garrido** [comment]
@MJWainwright this was removed, can you check the test server

**Comment by MJWainwright** [comment]
Checked! yes, the MyData tab no longer appears.

![image](https://user-images.githubusercontent.com/72507850/104020965-e520e200-51b5-11eb-86cf-cd4a0e40762d.png)
