### ISSUE TITLE
Tables are missing in Worksheet when project published as Fully Public

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#54]
For some reason the tables are not displaying when I look at a project that was published as fully public to the database
![image](https://user-images.githubusercontent.com/72507850/103903760-38caf700-50f4-11eb-8c16-40ce40a1217a.png)

**Comment by damian-garrido** [comment]
@MJWainwright i think this is resolved on the test server, can you check if true?
i publish a project, one with emojis. can you do the same?

**Comment by MJWainwright** [comment]
I went into a previous project, published it "fully public" then added a review finding and did the CERQual assessment. When I look on the database, the finding I added does not appear! I shared the project with you "THE IMPACT OF CHRONIC BREATHLESSNESS ON THE SOCIAL LIVES OF ADULTS IN CITIES: A QUALITATIVE EVIDENCE SYNTHESIS"
![Uploading image.png…]()

**Comment by damian-garrido** [comment]
perfect, got it!

**Comment by damian-garrido** [comment]
@MJWainwright now are available on the test server,
you can check this http://isoqf-test.epistemonikos.org/preview/isoq/789973411185f144/5f80b1e79a1a3ccb3b5ea174/public
or if you have one published as public you need to re-publish it for the tables and references are displayed.

**Comment by MJWainwright** [comment]
I couldn't seem to do it by just republishing an existing project (the tables would not appear), but I created a whole new project and yes the tables appeared and I checked each option and they are all displaying correctly!

**Comment by damian-garrido** [comment]
@MJWainwright can i access using your account to see if there any problems when you republish

**Comment by MJWainwright** [comment]
You mean on the test server right?

**Comment by damian-garrido** [comment]
aha

**Comment by MJWainwright** [comment]
Yes, on test server you can

**Comment by damian-garrido** [comment]
its seems you have your password, can you share this with me by email.
saludos

**Comment by damian-garrido** [comment]
can you check this again, i republish some of your projects and the tables appears.

**Comment by MJWainwright** [comment]
Checked. Looks good
