### ISSUE TITLE
Licence info missing from iSoQs published to database

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#55]
![image](https://user-images.githubusercontent.com/72507850/103904195-db837580-50f4-11eb-97ef-995a68742223.png)

The licence info is missing

**Comment by MJWainwright** [comment]
Just to clarify Damian, all of these "when published to database" comments are coming from the perspective of someone opening the project from the browse tab (e.g. as a member of the public, not the creator of the project)

**Comment by damian-garrido** [comment]
@MJWainwright now its displayed on test server

**Comment by MJWainwright** [comment]
Checked. Looks good.
