### ISSUE TITLE
Add "Beta Version" to homepage 

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#72]
Hi Damian, at the meeting I suggested adding "limited research" next to large iSoQ (below) on the homepage. But what do you think of calling it Beta Version instead?
![image](https://user-images.githubusercontent.com/72507850/105388640-cfc4a280-5c0e-11eb-915f-d853175b1e95.png)

**Comment by damian-garrido** [comment]
Beta or pre-release its ok.
for me, limited research was confusing, but maybe for your colleagues its more easy to understand rather than beta.
what do you think?

**Comment by MJWainwright** [comment]
Let's go with Beta version

**Comment by MJWainwright** [comment]
Checked. All good. You can close this ticket
