### ISSUE TITLE
Add message about being in limited release phase on login page

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#73]
Can we please add the following text to the login page, maybe highlighted in a pink box or something so it stands at the top of the page?

**iSoQ is currently being tested on real reviews. If you would like to use this beta version on your own review, please contact us to request an account (isoq@epistemonikos.org). If you already have an account, just login.**

![image](https://user-images.githubusercontent.com/72507850/105389704-1070eb80-5c10-11eb-9db4-f6cbf55bcf98.png)

**Comment by damian-garrido** [comment]
what do you think about add a new tab for contacts or another related tasks
between Help and Login add Contact tab

**Comment by MJWainwright** [comment]
I don't want to add a new tab. If we add a new tab all of my help videos will be out of date.

**Comment by MJWainwright** [comment]
Looks good. you can close this ticket.
