### ISSUE TITLE
Replace email address on Help page with new isoq epistemonikos email

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#74]
![image](https://user-images.githubusercontent.com/72507850/105389953-69408400-5c10-11eb-8a4a-1b52ba7a54ae.png)

Please remove Simon's email address and replace with the new email address for iSoQ. Thanks!

**Comment by damian-garrido** [comment]
i think in a way this issue is related to issue #73 
can you check my comments on the related issue? @MJWainwright

**Comment by MJWainwright** [comment]
I think these two issues are separate. We need the email address updated on the help page (this ticket) and we need a standing banner or box above the login box to explain that people just can't create an account for themselves (ticket 73)

**Comment by MJWainwright** [comment]
Checked. all good. You can close this ticket
