### ISSUE TITLE
Add banner on login page about recent updates and need to clear cache

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#75]
Please create a banner that will appear on the login page to alert the user that there has been an update and they need to clear their cache. Test below

**We've made some updates to the iSoQ server to improve your experience. To be sure you see these changes, clear your cache for the site before logging-in. Not sure how to clear the cache? Watch this video.**

I will make a little video and send you the link to add in due course. The way you showed me (F12, hold refresh button and select clear cache and hard reload), is that the same way no matter what browser someone is using? (I am using Chrome)

**Comment by damian-garrido** [comment]
for clear cache, you could also use Ctrl+Shift+R in chrome/firefox
for mac user, Cmd+Shift+R should work, i think.

**Comment by MJWainwright** [comment]
Ok thanks for that info!

**Comment by MJWainwright** [comment]
I think we have found a solution to this issue and no longer need users to clear cache. I am closing
