### ISSUE TITLE
Login password not working and recover password not working

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#76]
@damian-garrido 

I user reached out to me this morning saying she could not get into her account (being told either the password or user was not right). I tried using her credentials and could login so I asked her to check that she did not accidentally include any spaces when she copied and pasted. But now I am unable to login. It is not accepting my password. AND I am clicking "recover" in the reset your password box and nothing is happening.

**Comment by MJWainwright** [comment]
I was getting confused with the password, so that's sorted. But the recover password was still not working on the production site. Is that because you haven't made that update yet? On Monday could you make sure there is a complete update of all the features we've fixed and finalized?

**Comment by damian-garrido** [comment]
now its fixed on production

**Comment by MJWainwright** [comment]
Checked. All good
