### ISSUE TITLE
Print and export features are missing on projects accessed via Browse

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#77]
Hi Damian,

I just noticed that when a project is published to the iSoQ database, the browsing user is missing the options to export and print.  The person who accesses a published iSoQ via the database needs to be able to have the same options for printing and exporting as the user who is accessing their project internally.

iSoQ page - print/export. Export to MS word, Export references. and print or save as PDF
Worksheets  print/export. Export to MS word, and print or save as PDF

**Comment by ranazahroh** [comment]
Hi, @damian-garrido, the debugging seems to work but what appears is not consistent, for example on "National implementation of the World Health Organization Model List(s) of Essential Medicines- a qualitative evidence synthesis" project, headings of evidence profile and summary of findings appears, despite it does not appear when not exporting (on the isoq page). On "Test of publish function" project, evidence profile appears despite no data on the dashboard. Can you make the exported data/printed data be consistent with what appears on the isoq dashboard?
