### ISSUE TITLE
New projects are being given very strange dates when published

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#78]
See below: I published a bunch of projects and some are being labelled as 1970!

![image](https://user-images.githubusercontent.com/72507850/105630687-7e9cf480-5e42-11eb-9d78-77c46191d668.png)

**Comment by damian-garrido** [comment]
i think this projects is very oldery, so, they dont have this value on the database, so by default, the default date is printed.
now every new project should have this field and always show a correct date.
one option to fix the date is jus updating any content on the project, so this will create this attribute and fix de visualization of the date

**Comment by MJWainwright** [comment]
Hi Damian, that wasn't the case though. They weren't old projects they were completely new projects. I made them for the purpose of the help video 2 days ago.

**Comment by damian-garrido** [comment]
mmm, im gonna check

**Comment by damian-garrido** [comment]
confirm that happen on production and test.
im gonna fix this.

**Comment by MJWainwright** [comment]
Checked. all good on production server. You can close this ticket
