### ISSUE TITLE
Please add this text to the bottom of Help page

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#81]
The following should appear below the list of help videos. "GRADE-CERQual Webinars" is the heading (use same size and font as other headings on this page. Please add the hyperlinks for each webpage
![image](https://user-images.githubusercontent.com/72507850/105900529-156cdb00-6014-11eb-9f72-3fd4e0b206e4.png)

**GRADE-CERQual Webinars 

- Access the Cochrane Training Webinar on GRADE-CERQual here https://training.cochrane.org/resource/grade-cerqual-webinar

- For information on upcoming live GRADE-CERQual webinars visit https://www.cerqual.org/upcoming-events/**

**Comment by MJWainwright** [comment]
Checked. All good. Except it would be nice to have a bit of white space at the bottom after the last line. Right now the page ends right on the last line of text which looks a bit weird. 
![image](https://user-images.githubusercontent.com/72507850/114206857-a97fea80-9953-11eb-8ced-2b0aea3ed88b.png)

**Comment by damian-garrido** [comment]
im gona to create a new ticket for this and close this one.
