### ISSUE TITLE
Assessment not Completed Button is missing on Worksheet for overall assessment

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#85]
Hi Damian,

In making the help video yesterday I noticed an error in the worksheet. Each of the buttons says "Assessment not Completed" and then once completed says "Edit". This rule should be the same for the overall asessment of confidence (the last column). But currently it is not. See below:
![image](https://user-images.githubusercontent.com/72507850/106268862-98b04b80-6223-11eb-82e4-3434a63a02d1.png)

Until the user completes the final assessment the button should say "Assessment not Completed" - the text "explanation no yet added" should not appear. When the user completes it it should change to the Edit button.

**Comment by MJWainwright** [comment]
@damian-garrido . Any update on this ticket?

**Comment by MJWainwright** [comment]
@damian-garrido . Damian can we fix this this week? I have a workshop in two weeks and it will reduce confusion among participants if this is fixed in time.

**Comment by damian-garrido** [comment]
@MJWainwright could you check if this issue is solved to you

**Comment by MJWainwright** [comment]
@damian-garrido I checked on test server without clearing cache and yes it worked, both on an existing project, and on a new project. The button appears correctly, and also the explanation disappears as it should when I click "clear my selection"

We're good to publish to the production server! Thanks

**Comment by damian-garrido** [comment]
excelent! that are a good news!
