### ISSUE TITLE
Urgent! Create account link must be disabled from notification email

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#86]
Dear Damian,

A user has managed to create their own account! At this stage nobody should be able to create their own account so that function needs to be disabled. What happened was the following:

Claire shared with a colleague who did not yet have an account
The colleague received the following email and was able to create their account.
“Dear colleague,
Claire (claire.glenton@fhi.no) has invited you to the project "Healthcare workersâ€™ perceptions  and experiences of communicating with people over 50 about vaccination: a qualitative evidence synthesis" in iSoQ (the GRADE-CERQUAL Interactive Summary of Qualitative Findings Tool).

To access the shared project you need to create an account in iSoQ. Once you have an account you will find the shared project in "My Workspace".

Click the following link to create an iSoQ account https://isoq.epistemonikos.org/create_an_account?o=593552cbe77861fc&p=5ff4149fda97245fcb706b5d&r=1

Thanks!

GRADE-CERQual iSoQ - Powered by Epistemonikos”

This must be disabled, can you do it today?

Replace the text with:
“Dear colleague,
Claire (claire.glenton@fhi.no) has invited you to the project "                  " in iSoQ (the GRADE-CERQUAL Interactive Summary of Qualitative Findings Tool).

iSoQ is currently in the beta testing phase so to create an account you need to contact us at isoq@epistemonikos.org. We will create your account and send you your login details. When you login you will find the shared project in "My Workspace". 

Thanks!

GRADE-CERQual iSoQ - Powered by Epistemonikos”

**Comment by damian-garrido** [comment]
i made the change, can you check if its ok?

**Comment by MJWainwright** [comment]
@damian-garrido Nothing has changed. It is the same as before so still wrong.

**Comment by damian-garrido** [comment]
hi @MJWainwright 
i made a test and i get the following

![image](https://user-images.githubusercontent.com/25389333/107068557-8acc6e80-67bf-11eb-9718-5d646105c7ba.png)

**Comment by MJWainwright** [comment]
The text is not right. I provided alternative text above. But I'll repeat it here:

“Dear colleague,
[name]  has invited you to the project " " in iSoQ (the GRADE-CERQUAL Interactive Summary of Qualitative Findings Tool).

**iSoQ is currently in the beta testing phase so to create an account you need to contact us at isoq@epistemonikos.org. We will create your account and send you your login details. When you login you will find the shared project in "My Workspace".**

Thanks!

GRADE-CERQual iSoQ - Powered by Epistemonikos”

**Comment by damian-garrido** [comment]
![image](https://user-images.githubusercontent.com/25389333/107236260-4b429400-6a04-11eb-93a6-37c4abeb6bb5.png)

i add the missing part of the email.

**Comment by MJWainwright** [comment]
Tested. Looks good! Thanks:)
