### ISSUE TITLE
Entire project frozen (showstopper issue)

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#88]
Hi Damian,

A user's project has completely frozen. They shared it with me and indeed it's totally frozen on the iSoQ tab. you can't move to any tabs or take any action on the page. Unfortunately the user is not responding to my requests for futher information and I fear may have abandoned their attempt to use iSoQ. Still, is there a way to investigate this int he background?

Here's what they first wrote me:
"I have encountered a technical issue while uploading my characteristic table and also one more issue that year is not coming along with Author names."

"Now I am unable to view my data and project properties that I had filled earlier. It's directing me to the ISOQ page." 

I requested they do the following, but so far the only they've done is invite me to the project:
1) Can you please share the project with me? just give me right to "view only". Use the email address isoq@epistemonikos.org. If you prefer not to share the project with me, please take printscreen shots of what you are seeing (your table and your authors/year issue in the refs
2) Please send me your characteristics of studies table that you are trying to upload and describe the uploading problem to me in more detail
3) Please send the file for your references that you uploaded (RIS file/.txt)
4) Please tell me what reference management software you exported to RIS from.

I will email you separately with the information about this specific account

**Comment by MJWainwright** [comment]
@damian-garrido . Any advancement on resolving this one?

**Comment by damian-garrido** [comment]
"I have encountered a technical issue while uploading my characteristic table and also one more issue that year is not coming along with Author names."
i think the RIS file dont have this value, so, the year is not displayed.

"Now I am unable to view my data and project properties that I had filled earlier. It's directing me to the ISOQ page."
i think i fix this problem on database. could you ask if she/he can access to the project?

**Comment by MJWainwright** [comment]
Hi Damian, this user is no longer in touch (hasn't responded to my emails). I think we can close this ticket and if the problem is reported again I will submit a new ticket.
