### ISSUE TITLE
Enhancement request for v.1 - export/print all evidence profiles

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#89]
Claire is the first user to test iSoQ through the whole process of producing a review for a decision-making context and she has made a really important observation:

When she is finished she needs to not only print or export her iSoQ table but also an evidence profile table with ALL the findings. At the moment, a user can only download an evidence profile table for one finding at a time. So claire had to do 15 downloads and then manually copy and paste the tables into one document. Producing an Evidence Profile table including all findings is a very common output of a synthesis using CERQual so I think it is really worth making this possible for v.1. 
Is it complex to achieve? Basically merging all the Evidence profile tables (just the first table of the Worksheet called Evidence Profile), into one Evidence Profile Table? If it is doable I would suggest this feature be available on the iSoQ tab:

![image](https://user-images.githubusercontent.com/72507850/109529852-01524880-7aae-11eb-874a-2136a8248044.png)

![image](https://user-images.githubusercontent.com/72507850/109530186-5db56800-7aae-11eb-8e38-3dca19ccfafa.png)

**Comment by MJWainwright** [comment]
@damian-garrido Hey Damian, how are we doing with this enhancement? It's a priority for our launch of v.1

**Comment by damian-garrido** [comment]
hi
im going to put this on my tops. hope for the next week i can work on this.

**Comment by damian-garrido** [comment]
hi @MJWainwright !
i made un update on this.
can you check this on the test server and tell me if the information is ok and how do you prefer display the table content.
for the moment this its only available on the print version until we have a definition on how this would be displayed.

**Comment by MJWainwright** [comment]
I think we have resolved this for v.1 so I'm closing
