### ISSUE TITLE
Error when duplicating a shared project - data missing (urgent)

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#91]
Hi Damian,

I shared a test project (for workshop) in my personal iSoQ with the account for the GRADE-CERQual project group. This was fine. But then from the GRADE-CERQual iSoQ account I duplicated the project and for some reason, only the project properties appear, not all the My Data or iSoQ or worksheets.

I'm going to share this project with you so you can see and hopefully it is a quick fix.

Thanks!
Megan

**Comment by damian-garrido** [comment]
wow!
i check this and yeah, this dont copy the data.
i have a clue on what's happening here.
im gonna check and try to fix ASAP

**Comment by MJWainwright** [comment]
Great, thanks!

**Comment by damian-garrido** [comment]
hi @MJWainwright 
i think i found the bug and fix it.
can you check on the server test.

**Comment by MJWainwright** [comment]
Yes, it is fixed! Are you by chance able to update the production server so I can use this function for my course tomorrow?

**Comment by MJWainwright** [comment]
@damian-garrido

**Comment by MJWainwright** [comment]
@damian-garrido 

Hi Damian, I tested this out yesterday in the course, and strangely it worked perfectly in only the 1st of the 4 duplicates, but in 2nd, 3rd and 4th the extracted data was missing. I have invited you to each project so you can see. 
![image](https://user-images.githubusercontent.com/72507850/110701144-b55b7e00-81e8-11eb-85e5-d2c8bd073ce4.png)

**Comment by MJWainwright** [comment]
@damian-garrido - should we make sure this is sorted out before publishing to the production server?

**Comment by MJWainwright** [comment]
@damian-garrido Hi Damian, just following-up on this.

**Comment by MJWainwright** [comment]
I just reproduced the error.

1) User 1 created a project on the test server,added all info in My data, created one finding and put in the extracted table in the worksheet for that finding.

2) User 1 shared the project with User 2

3) User 2 created a shared copy of the project. This shared copy has missing data. in this case the characteristics of studies is missing and the extracted data.

Here is the project that user 2 received from user 1:
![image](https://user-images.githubusercontent.com/72507850/114205737-8a348d80-9952-11eb-9592-822fe48871c4.png)

![image](https://user-images.githubusercontent.com/72507850/114205780-96204f80-9952-11eb-8e3a-e823400900d8.png)


Here is what the copy looks like:
![image](https://user-images.githubusercontent.com/72507850/114205697-79841780-9952-11eb-968a-5bf551c3b9a5.png)

![image](https://user-images.githubusercontent.com/72507850/114205676-738e3680-9952-11eb-8c3d-17f38c341538.png)

**Comment by damian-garrido** [comment]
oh no!
(user1)
i create another project and load some data and create a finding.
![image](https://user-images.githubusercontent.com/25389333/114206914-d3241c00-9929-11eb-9f47-5cac6b6a2a90.png)
the tables looks good.
share the project.
(user2)
the other user see the same structure
![image](https://user-images.githubusercontent.com/25389333/114207236-27c79700-992a-11eb-924a-640a36938185.png)
no data was missing.
also, create a copy of the shared project
![image](https://user-images.githubusercontent.com/25389333/114207677-a15f8500-992a-11eb-800b-5dc3c6447ec2.png)
and check the content of this
![image](https://user-images.githubusercontent.com/25389333/114207750-ba683600-992a-11eb-9eb3-5cb7c546aeda.png)

could you clean your cache.
i made an update with this and i hope this will be your last time you need to clean your cache

**Comment by MJWainwright** [comment]
I cleared the cache, and did it all again! It's fixed! Can you publish to the production server?
