### ISSUE TITLE
Error in create column headings when new heading is added and order changed

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#92]
Hi Damian, I encountered the following issue:

- I created a Table manually with 5 columns
- I began entering data
- I decided I needed another column and that this column should be moved to second place in the list (so I added a column and then dragged and dropped it come second in the list). 
- The new column that I created and moved to second place (column#1) does not show in the table, however I do see it when I click on edit/add columns.

Here you see it Column #1 (by the way, I'm not sure why we have column 0. it is a bit weird to not just start at 1)

![image](https://user-images.githubusercontent.com/72507850/110240364-76f16500-7f43-11eb-9950-f06e07e5179b.png)

Here, in the table you can see that Column #1 (o objetivo da pesquisa era claro?) does not appear
![image](https://user-images.githubusercontent.com/72507850/110240425-c3d53b80-7f43-11eb-85b6-97568b7ef3d5.png)

But then it does appear when I click the edit button to enter data
![image](https://user-images.githubusercontent.com/72507850/110240446-d8b1cf00-7f43-11eb-9458-2b375f9f937c.png)

But then when I add the answer to the Column #1 question (o objetivo da pesquisa era claro). It copies my response in the previous question box (column 0 - O disenho do projeto...)

![image](https://user-images.githubusercontent.com/72507850/110240487-06971380-7f44-11eb-8677-25afc06c8916.png)

If I click Save the column and the answer I put in still does not appear in the table

Something weird is happening between Column #0 and Column #1?

To get around the problem, I just deleted the column I created and changed the name of column #0 (since I was thinking of deleting that one anyway). However, what then happens is the name is changed but all the data I entered is lost:
![image](https://user-images.githubusercontent.com/72507850/110240603-a81e6500-7f44-11eb-80e2-e5ae4241f119.png)

**Comment by damian-garrido** [comment]
hi @MJWainwright 
can you check if this happen also in the test server?
i try to reproduce and i dont have this issue, at least to the part when you entering data an then create a new column.

i create a new project, 3 references, first create a five column table and add some data
![image](https://user-images.githubusercontent.com/25389333/110332288-e8dab480-7ffe-11eb-8e6b-1b2d3de2a3c5.png)

then add a new column and change to the second position
![image](https://user-images.githubusercontent.com/25389333/110332476-1de70700-7fff-11eb-9334-e3a782f04f5f.png)

the new column is displayed and the data is still there
![image](https://user-images.githubusercontent.com/25389333/110332498-28090580-7fff-11eb-99d2-b14f869de55e.png)

add data to the new column and change one data of another column (columna nr 4)
![image](https://user-images.githubusercontent.com/25389333/110332578-43741080-7fff-11eb-8357-4de6bda93b39.png)

this issue happen when you create a new project or work in a old one?
if happening with an old one i recommend to start a new one and test if this happening.

**Comment by MJWainwright** [comment]
It was a new project, but I will test again and let you know. I will have more time to test later this week

**Comment by MJWainwright** [comment]
I can't seem to reproduce it on the test site or the production server! So I guess for now we can close and if I spot it again I will resubmit a ticket. Thanks!

**Comment by MJWainwright** [comment]
@damian-garrido. Has this ticket been closed and updated to production server?

**Comment by damian-garrido** [comment]
the ticket its not closed until you say we can close.
for the moment, this issue was fixed in both servers.
could you check first on test server and then in production?

**Comment by MJWainwright** [comment]
But see above, I said 19 days ago it was fixed and you can close, but it was never closed. So yes, please close!:)
