### ISSUE TITLE
Refs missing from exported Worksheet

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#94]
Hiya! The refs have disappeared again from the exported worksheet Evidence Profile Table

![image](https://user-images.githubusercontent.com/72507850/110385878-6c27f480-8057-11eb-95a1-76f7e80bec9f.png)

**Comment by damian-garrido** [comment]
could you provide more information?
when happen this? after save, or remove or cloning?

**Comment by MJWainwright** [comment]
It is happening on cloned/duplicated projects. I've invited you to the original "

"GRADE-CERQual Workshop Exercise: Vaccination Example (Portuguese)"

and to the copies:

Group 1 GRADE-CERQual Workshop Exercise: Vaccination Example (Portuguese)

Group 2 GRADE-CERQual Workshop Exercise: Vaccination Example (Portuguese)

Group 3 GRADE-CERQual Workshop Exercise: Vaccination Example (Portuguese)

Group 4 GRADE-CERQual Workshop Exercise: Vaccination Example (Portuguese)
--

You'll see that in the original the refs appear when you go into print/export mode, but in the duplicates they don't.

**Comment by damian-garrido** [comment]
goi it
i think to know whats happening

**Comment by MJWainwright** [comment]
@damian-garrido - is there a fix I can check for this?

**Comment by damian-garrido** [comment]
please check on the test server, i think this is also fixed

**Comment by MJWainwright** [comment]
Nope, still doing it. 
User 1 created a project and shared with user 2
User 2 copies the project

The copied project does not show the references in the evidence profile when the user clicks print/export.

Here is edit mode you see the references:
![image](https://user-images.githubusercontent.com/72507850/114214547-59f1ec80-995c-11eb-999e-7666415f6d37.png)


But then when you click "print/export" and the references are not there
![image](https://user-images.githubusercontent.com/72507850/114214595-670edb80-995c-11eb-94be-cfc845e5e920.png)

**Comment by damian-garrido** [comment]
now that you have you cache cleaned, can you check on this again please

**Comment by MJWainwright** [comment]
No this bug still appears on the Test server. I followed the same steps

- User 1 created a project - references appear in evidence profile table in print/edit mode
- User 1 shared that project with User 2 - references appear in evidence profile table in print/edit mode
**- User 2 duplicates the project - references DO NOT appear in the evidence profile table in print/edit mode of the duplicated project**
![image](https://user-images.githubusercontent.com/72507850/115987784-6efe8a80-a5ae-11eb-86fe-26607cd6a7f7.png)
![image](https://user-images.githubusercontent.com/72507850/115987790-7887f280-a5ae-11eb-96f0-fd944faeb575.png)

**Comment by MJWainwright** [comment]
@damian-garrido  - just so you know, this bug is still active. See below:
![image](https://user-images.githubusercontent.com/72507850/117886846-b7ed5900-b2a7-11eb-87bc-e3817d7d961f.png)

**Comment by MJWainwright** [comment]
@damian-garrido Any progress on this bug?

**Comment by damian-garrido** [comment]
sorry my delay, today i found and fixed this.
could you check on test server please?

**Comment by MJWainwright** [comment]
@damian-garrido . Checked, all good. It is fixed on the test server and applied itself to both new and old projects. can we add this to the production server update early next week?
