### ISSUE TITLE
Bug - text from a different component appearing in explanation box of another

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#98]
Hi Damian,

I'm preparing for another workshop and have found a weird bug.

First I completed methodological limitations component - minor concerns and added explanation
Secondly I completed coherence - no/very minor concerns and did not add an explanation
Thirdly I tried to complete adequacy - serious concerns and first tried to save without adding an explanation. When the pop-up appeared I clicked "add it now", but as soon as I edited the text in the explanation box (e.g. deleting the ...) suddenly the explanation text from the methodological limitations component appeared in the box!

![image](https://user-images.githubusercontent.com/72507850/115986868-4d030900-a5aa-11eb-916d-938b4b55f54d.png)
![image](https://user-images.githubusercontent.com/72507850/115986993-0e218300-a5ab-11eb-9258-f47702437ce4.png)
![image](https://user-images.githubusercontent.com/72507850/115986998-12e63700-a5ab-11eb-818f-16001d9a0386.png)
![image](https://user-images.githubusercontent.com/72507850/115987025-3a3d0400-a5ab-11eb-8651-f0e87a9baa39.png)

I think what provokes this bug is clicking Save without and explanation and then clicking "add it now"

**Comment by damian-garrido** [comment]
i try to reproduce it but i cant, could you check in test server if this bug is still alive?

**Comment by MJWainwright** [comment]
@damian-garrido It is still doing it. Do you want to have a short call so I can demo it?

**Comment by MJWainwright** [comment]
Ok thanks!

**Comment by damian-garrido** [comment]
could you check if this is still a bug
thnks

**Comment by MJWainwright** [comment]
Checked, all good on both the test and production server

**Comment by MJWainwright** [comment]
As this appears fixed on productions server I am closing

**Comment by MJWainwright** [comment]
Fixed on production server
