### ISSUE TITLE
Explanation does not delete when overall assessment is cleared

### ISSUE THREAD

**Issue by MJWainwright** [epistemonikos/isoq#99]
![image](https://user-images.githubusercontent.com/72507850/116271625-10850800-a778-11eb-83f4-b09014ee0dc5.png)
![image](https://user-images.githubusercontent.com/72507850/116271662-18dd4300-a778-11eb-9aca-eee975a060c5.png)

**Comment by MJWainwright** [comment]
Hi Damian, I don't think you have implemented this on the production server. Can you do so now please?

**Comment by damian-garrido** [comment]
can you check if now on production server? thanks

**Comment by MJWainwright** [comment]
I just checked production server without clearing cache, the error is still there on old and new projects. I will try clearing cache now.
